CURRENCIES = [
    {'code': 'USD', 'name': 'US Dollar', 'symbol': '$'},
    {'code': 'EUR', 'name': 'Euro', 'symbol': '€'},
    {'code': 'GBP', 'name': 'British Pound', 'symbol': '£'},
    {'code': 'INR', 'name': 'Indian Rupee', 'symbol': '₹'},
    {'code': 'JPY', 'name': 'Japanese Yen', 'symbol': '¥'},
    {'code': 'CAD', 'name': 'Canadian Dollar', 'symbol': 'C$'},
    {'code': 'AUD', 'name': 'Australian Dollar', 'symbol': 'A$'},
    {'code': 'CHF', 'name': 'Swiss Franc', 'symbol': 'CHF'},
    {'code': 'CNY', 'name': 'Chinese Yuan', 'symbol': '¥'},
    {'code': 'SGD', 'name': 'Singapore Dollar', 'symbol': 'S$'},
    {'code': 'SEK', 'name': 'Swedish Krona', 'symbol': 'kr'},
    {'code': 'NOK', 'name': 'Norwegian Krone', 'symbol': 'kr'},
    {'code': 'DKK', 'name': 'Danish Krone', 'symbol': 'kr'},
    {'code': 'PLN', 'name': 'Polish Zloty', 'symbol': 'zł'},
    {'code': 'CZK', 'name': 'Czech Koruna', 'symbol': 'Kč'},
    {'code': 'HUF', 'name': 'Hungarian Forint', 'symbol': 'Ft'},
    {'code': 'RON', 'name': 'Romanian Leu', 'symbol': 'lei'},
    {'code': 'BGN', 'name': 'Bulgarian Lev', 'symbol': 'лв'},
    {'code': 'HRK', 'name': 'Croatian Kuna', 'symbol': 'kn'},
    {'code': 'RUB', 'name': 'Russian Ruble', 'symbol': '₽'},
    {'code': 'TRY', 'name': 'Turkish Lira', 'symbol': '₺'},
    {'code': 'BRL', 'name': 'Brazilian Real', 'symbol': 'R$'},
    {'code': 'MXN', 'name': 'Mexican Peso', 'symbol': '$'},
    {'code': 'ARS', 'name': 'Argentine Peso', 'symbol': '$'},
    {'code': 'CLP', 'name': 'Chilean Peso', 'symbol': '$'},
    {'code': 'COP', 'name': 'Colombian Peso', 'symbol': '$'},
    {'code': 'PEN', 'name': 'Peruvian Sol', 'symbol': 'S/'},
    {'code': 'ZAR', 'name': 'South African Rand', 'symbol': 'R'},
    {'code': 'EGP', 'name': 'Egyptian Pound', 'symbol': '£'},
    {'code': 'MAD', 'name': 'Moroccan Dirham', 'symbol': 'د.م.'},
    {'code': 'NGN', 'name': 'Nigerian Naira', 'symbol': '₦'},
    {'code': 'KES', 'name': 'Kenyan Shilling', 'symbol': 'KSh'},
    {'code': 'GHS', 'name': 'Ghanaian Cedi', 'symbol': '₵'},
    {'code': 'TZS', 'name': 'Tanzanian Shilling', 'symbol': 'TSh'},
    {'code': 'UGX', 'name': 'Ugandan Shilling', 'symbol': 'USh'},
    {'code': 'ETB', 'name': 'Ethiopian Birr', 'symbol': 'Br'},
    {'code': 'ZMW', 'name': 'Zambian Kwacha', 'symbol': 'ZK'},
    {'code': 'BWP', 'name': 'Botswanan Pula', 'symbol': 'P'},
    {'code': 'MWK', 'name': 'Malawian Kwacha', 'symbol': 'MK'},
    {'code': 'MZN', 'name': 'Mozambican Metical', 'symbol': 'MT'},
    {'code': 'AED', 'name': 'UAE Dirham', 'symbol': 'د.إ'},
    {'code': 'SAR', 'name': 'Saudi Riyal', 'symbol': '﷼'},
    {'code': 'QAR', 'name': 'Qatari Riyal', 'symbol': '﷼'},
    {'code': 'KWD', 'name': 'Kuwaiti Dinar', 'symbol': 'د.ك'},
    {'code': 'BHD', 'name': 'Bahraini Dinar', 'symbol': '.د.ب'},
    {'code': 'OMR', 'name': 'Omani Rial', 'symbol': '﷼'},
    {'code': 'JOD', 'name': 'Jordanian Dinar', 'symbol': 'د.ا'},
    {'code': 'LBP', 'name': 'Lebanese Pound', 'symbol': '£'},
    {'code': 'ILS', 'name': 'Israeli Shekel', 'symbol': '₪'},
    {'code': 'IRR', 'name': 'Iranian Rial', 'symbol': '﷼'},
    {'code': 'IQD', 'name': 'Iraqi Dinar', 'symbol': 'د.ع'},
    {'code': 'KRW', 'name': 'South Korean Won', 'symbol': '₩'},
    {'code': 'TWD', 'name': 'Taiwan Dollar', 'symbol': 'NT$'},
    {'code': 'HKD', 'name': 'Hong Kong Dollar', 'symbol': 'HK$'},
    {'code': 'MYR', 'name': 'Malaysian Ringgit', 'symbol': 'RM'},
    {'code': 'THB', 'name': 'Thai Baht', 'symbol': '฿'},
    {'code': 'IDR', 'name': 'Indonesian Rupiah', 'symbol': 'Rp'},
    {'code': 'PHP', 'name': 'Philippine Peso', 'symbol': '₱'},
    {'code': 'VND', 'name': 'Vietnamese Dong', 'symbol': '₫'},
    {'code': 'LAK', 'name': 'Laotian Kip', 'symbol': '₭'},
    {'code': 'KHR', 'name': 'Cambodian Riel', 'symbol': '៛'},
    {'code': 'MMK', 'name': 'Myanmar Kyat', 'symbol': 'K'},
    {'code': 'BDT', 'name': 'Bangladeshi Taka', 'symbol': '৳'},
    {'code': 'LKR', 'name': 'Sri Lankan Rupee', 'symbol': '₨'},
    {'code': 'NPR', 'name': 'Nepalese Rupee', 'symbol': '₨'},
    {'code': 'PKR', 'name': 'Pakistani Rupee', 'symbol': '₨'},
    {'code': 'AFN', 'name': 'Afghan Afghani', 'symbol': '؋'},
    {'code': 'UZS', 'name': 'Uzbek Som', 'symbol': 'лв'},
    {'code': 'KZT', 'name': 'Kazakhstani Tenge', 'symbol': '₸'},
    {'code': 'KGS', 'name': 'Kyrgyzstani Som', 'symbol': 'лв'},
    {'code': 'TJS', 'name': 'Tajikistani Somoni', 'symbol': 'SM'},
    {'code': 'TMT', 'name': 'Turkmenistani Manat', 'symbol': 'T'},
    {'code': 'MNT', 'name': 'Mongolian Tugrik', 'symbol': '₮'},
    {'code': 'NZD', 'name': 'New Zealand Dollar', 'symbol': 'NZ$'},
    {'code': 'FJD', 'name': 'Fijian Dollar', 'symbol': 'FJ$'},
    {'code': 'TOP', 'name': 'Tongan Paʻanga', 'symbol': 'T$'},
    {'code': 'WST', 'name': 'Samoan Tala', 'symbol': 'WS$'},
    {'code': 'VUV', 'name': 'Vanuatu Vatu', 'symbol': 'VT'},
    {'code': 'PGK', 'name': 'Papua New Guinean Kina', 'symbol': 'K'},
    {'code': 'SBD', 'name': 'Solomon Islands Dollar', 'symbol': 'SI$'},
]

COUNTRIES = [
    {'code': 'AD', 'name': 'Andorra', 'phone_code': '+376'},
    {'code': 'AE', 'name': 'United Arab Emirates', 'phone_code': '+971'},
    {'code': 'AF', 'name': 'Afghanistan', 'phone_code': '+93'},
    {'code': 'AG', 'name': 'Antigua and Barbuda', 'phone_code': '+1'},
    {'code': 'AI', 'name': 'Anguilla', 'phone_code': '+1'},
    {'code': 'AL', 'name': 'Albania', 'phone_code': '+355'},
    {'code': 'AM', 'name': 'Armenia', 'phone_code': '+374'},
    {'code': 'AO', 'name': 'Angola', 'phone_code': '+244'},
    {'code': 'AQ', 'name': 'Antarctica', 'phone_code': '+672'},
    {'code': 'AR', 'name': 'Argentina', 'phone_code': '+54'},
    {'code': 'AS', 'name': 'American Samoa', 'phone_code': '+1'},
    {'code': 'AT', 'name': 'Austria', 'phone_code': '+43'},
    {'code': 'AU', 'name': 'Australia', 'phone_code': '+61'},
    {'code': 'AW', 'name': 'Aruba', 'phone_code': '+297'},
    {'code': 'AX', 'name': 'Åland Islands', 'phone_code': '+358'},
    {'code': 'AZ', 'name': 'Azerbaijan', 'phone_code': '+994'},
    {'code': 'BA', 'name': 'Bosnia and Herzegovina', 'phone_code': '+387'},
    {'code': 'BB', 'name': 'Barbados', 'phone_code': '+1'},
    {'code': 'BD', 'name': 'Bangladesh', 'phone_code': '+880'},
    {'code': 'BE', 'name': 'Belgium', 'phone_code': '+32'},
    {'code': 'BF', 'name': 'Burkina Faso', 'phone_code': '+226'},
    {'code': 'BG', 'name': 'Bulgaria', 'phone_code': '+359'},
    {'code': 'BH', 'name': 'Bahrain', 'phone_code': '+973'},
    {'code': 'BI', 'name': 'Burundi', 'phone_code': '+257'},
    {'code': 'BJ', 'name': 'Benin', 'phone_code': '+229'},
    {'code': 'BL', 'name': 'Saint Barthélemy', 'phone_code': '+590'},
    {'code': 'BM', 'name': 'Bermuda', 'phone_code': '+1'},
    {'code': 'BN', 'name': 'Brunei', 'phone_code': '+673'},
    {'code': 'BO', 'name': 'Bolivia', 'phone_code': '+591'},
    {'code': 'BQ', 'name': 'Caribbean Netherlands', 'phone_code': '+599'},
    {'code': 'BR', 'name': 'Brazil', 'phone_code': '+55'},
    {'code': 'BS', 'name': 'Bahamas', 'phone_code': '+1'},
    {'code': 'BT', 'name': 'Bhutan', 'phone_code': '+975'},
    {'code': 'BV', 'name': 'Bouvet Island', 'phone_code': '+47'},
    {'code': 'BW', 'name': 'Botswana', 'phone_code': '+267'},
    {'code': 'BY', 'name': 'Belarus', 'phone_code': '+375'},
    {'code': 'BZ', 'name': 'Belize', 'phone_code': '+501'},
    {'code': 'CA', 'name': 'Canada', 'phone_code': '+1'},
    {'code': 'CC', 'name': 'Cocos (Keeling) Islands', 'phone_code': '+61'},
    {'code': 'CD', 'name': 'Democratic Republic of the Congo', 'phone_code': '+243'},
    {'code': 'CF', 'name': 'Central African Republic', 'phone_code': '+236'},
    {'code': 'CG', 'name': 'Republic of the Congo', 'phone_code': '+242'},
    {'code': 'CH', 'name': 'Switzerland', 'phone_code': '+41'},
    {'code': 'CI', 'name': 'Côte d\'Ivoire', 'phone_code': '+225'},
    {'code': 'CK', 'name': 'Cook Islands', 'phone_code': '+682'},
    {'code': 'CL', 'name': 'Chile', 'phone_code': '+56'},
    {'code': 'CM', 'name': 'Cameroon', 'phone_code': '+237'},
    {'code': 'CN', 'name': 'China', 'phone_code': '+86'},
    {'code': 'CO', 'name': 'Colombia', 'phone_code': '+57'},
    {'code': 'CR', 'name': 'Costa Rica', 'phone_code': '+506'},
    {'code': 'CU', 'name': 'Cuba', 'phone_code': '+53'},
    {'code': 'CV', 'name': 'Cape Verde', 'phone_code': '+238'},
    {'code': 'CW', 'name': 'Curaçao', 'phone_code': '+599'},
    {'code': 'CX', 'name': 'Christmas Island', 'phone_code': '+61'},
    {'code': 'CY', 'name': 'Cyprus', 'phone_code': '+357'},
    {'code': 'CZ', 'name': 'Czech Republic', 'phone_code': '+420'},
    {'code': 'DE', 'name': 'Germany', 'phone_code': '+49'},
    {'code': 'DJ', 'name': 'Djibouti', 'phone_code': '+253'},
    {'code': 'DK', 'name': 'Denmark', 'phone_code': '+45'},
    {'code': 'DM', 'name': 'Dominica', 'phone_code': '+1'},
    {'code': 'DO', 'name': 'Dominican Republic', 'phone_code': '+1'},
    {'code': 'DZ', 'name': 'Algeria', 'phone_code': '+213'},
    {'code': 'EC', 'name': 'Ecuador', 'phone_code': '+593'},
    {'code': 'EE', 'name': 'Estonia', 'phone_code': '+372'},
    {'code': 'EG', 'name': 'Egypt', 'phone_code': '+20'},
    {'code': 'EH', 'name': 'Western Sahara', 'phone_code': '+212'},
    {'code': 'ER', 'name': 'Eritrea', 'phone_code': '+291'},
    {'code': 'ES', 'name': 'Spain', 'phone_code': '+34'},
    {'code': 'ET', 'name': 'Ethiopia', 'phone_code': '+251'},
    {'code': 'FI', 'name': 'Finland', 'phone_code': '+358'},
    {'code': 'FJ', 'name': 'Fiji', 'phone_code': '+679'},
    {'code': 'FK', 'name': 'Falkland Islands', 'phone_code': '+500'},
    {'code': 'FM', 'name': 'Micronesia', 'phone_code': '+691'},
    {'code': 'FO', 'name': 'Faroe Islands', 'phone_code': '+298'},
    {'code': 'FR', 'name': 'France', 'phone_code': '+33'},
    {'code': 'GA', 'name': 'Gabon', 'phone_code': '+241'},
    {'code': 'GB', 'name': 'United Kingdom', 'phone_code': '+44'},
    {'code': 'GD', 'name': 'Grenada', 'phone_code': '+1'},
    {'code': 'GE', 'name': 'Georgia', 'phone_code': '+995'},
    {'code': 'GF', 'name': 'French Guiana', 'phone_code': '+594'},
    {'code': 'GG', 'name': 'Guernsey', 'phone_code': '+44'},
    {'code': 'GH', 'name': 'Ghana', 'phone_code': '+233'},
    {'code': 'GI', 'name': 'Gibraltar', 'phone_code': '+350'},
    {'code': 'GL', 'name': 'Greenland', 'phone_code': '+299'},
    {'code': 'GM', 'name': 'Gambia', 'phone_code': '+220'},
    {'code': 'GN', 'name': 'Guinea', 'phone_code': '+224'},
    {'code': 'GP', 'name': 'Guadeloupe', 'phone_code': '+590'},
    {'code': 'GQ', 'name': 'Equatorial Guinea', 'phone_code': '+240'},
    {'code': 'GR', 'name': 'Greece', 'phone_code': '+30'},
    {'code': 'GS', 'name': 'South Georgia and the South Sandwich Islands', 'phone_code': '+500'},
    {'code': 'GT', 'name': 'Guatemala', 'phone_code': '+502'},
    {'code': 'GU', 'name': 'Guam', 'phone_code': '+1'},
    {'code': 'GW', 'name': 'Guinea-Bissau', 'phone_code': '+245'},
    {'code': 'GY', 'name': 'Guyana', 'phone_code': '+592'},
    {'code': 'HK', 'name': 'Hong Kong', 'phone_code': '+852'},
    {'code': 'HM', 'name': 'Heard Island and McDonald Islands', 'phone_code': '+672'},
    {'code': 'HN', 'name': 'Honduras', 'phone_code': '+504'},
    {'code': 'HR', 'name': 'Croatia', 'phone_code': '+385'},
    {'code': 'HT', 'name': 'Haiti', 'phone_code': '+509'},
    {'code': 'HU', 'name': 'Hungary', 'phone_code': '+36'},
    {'code': 'ID', 'name': 'Indonesia', 'phone_code': '+62'},
    {'code': 'IE', 'name': 'Ireland', 'phone_code': '+353'},
    {'code': 'IL', 'name': 'Israel', 'phone_code': '+972'},
    {'code': 'IM', 'name': 'Isle of Man', 'phone_code': '+44'},
    {'code': 'IN', 'name': 'India', 'phone_code': '+91'},
    {'code': 'IO', 'name': 'British Indian Ocean Territory', 'phone_code': '+246'},
    {'code': 'IQ', 'name': 'Iraq', 'phone_code': '+964'},
    {'code': 'IR', 'name': 'Iran', 'phone_code': '+98'},
    {'code': 'IS', 'name': 'Iceland', 'phone_code': '+354'},
    {'code': 'IT', 'name': 'Italy', 'phone_code': '+39'},
    {'code': 'JE', 'name': 'Jersey', 'phone_code': '+44'},
    {'code': 'JM', 'name': 'Jamaica', 'phone_code': '+1'},
    {'code': 'JO', 'name': 'Jordan', 'phone_code': '+962'},
    {'code': 'JP', 'name': 'Japan', 'phone_code': '+81'},
    {'code': 'KE', 'name': 'Kenya', 'phone_code': '+254'},
    {'code': 'KG', 'name': 'Kyrgyzstan', 'phone_code': '+996'},
    {'code': 'KH', 'name': 'Cambodia', 'phone_code': '+855'},
    {'code': 'KI', 'name': 'Kiribati', 'phone_code': '+686'},
    {'code': 'KM', 'name': 'Comoros', 'phone_code': '+269'},
    {'code': 'KN', 'name': 'Saint Kitts and Nevis', 'phone_code': '+1'},
    {'code': 'KP', 'name': 'North Korea', 'phone_code': '+850'},
    {'code': 'KR', 'name': 'South Korea', 'phone_code': '+82'},
    {'code': 'KW', 'name': 'Kuwait', 'phone_code': '+965'},
    {'code': 'KY', 'name': 'Cayman Islands', 'phone_code': '+1'},
    {'code': 'KZ', 'name': 'Kazakhstan', 'phone_code': '+7'},
    {'code': 'LA', 'name': 'Laos', 'phone_code': '+856'},
    {'code': 'LB', 'name': 'Lebanon', 'phone_code': '+961'},
    {'code': 'LC', 'name': 'Saint Lucia', 'phone_code': '+1'},
    {'code': 'LI', 'name': 'Liechtenstein', 'phone_code': '+423'},
    {'code': 'LK', 'name': 'Sri Lanka', 'phone_code': '+94'},
    {'code': 'LR', 'name': 'Liberia', 'phone_code': '+231'},
    {'code': 'LS', 'name': 'Lesotho', 'phone_code': '+266'},
    {'code': 'LT', 'name': 'Lithuania', 'phone_code': '+370'},
    {'code': 'LU', 'name': 'Luxembourg', 'phone_code': '+352'},
    {'code': 'LV', 'name': 'Latvia', 'phone_code': '+371'},
    {'code': 'LY', 'name': 'Libya', 'phone_code': '+218'},
    {'code': 'MA', 'name': 'Morocco', 'phone_code': '+212'},
    {'code': 'MC', 'name': 'Monaco', 'phone_code': '+377'},
    {'code': 'MD', 'name': 'Moldova', 'phone_code': '+373'},
    {'code': 'ME', 'name': 'Montenegro', 'phone_code': '+382'},
    {'code': 'MF', 'name': 'Saint Martin', 'phone_code': '+590'},
    {'code': 'MG', 'name': 'Madagascar', 'phone_code': '+261'},
    {'code': 'MH', 'name': 'Marshall Islands', 'phone_code': '+692'},
    {'code': 'MK', 'name': 'North Macedonia', 'phone_code': '+389'},
    {'code': 'ML', 'name': 'Mali', 'phone_code': '+223'},
    {'code': 'MM', 'name': 'Myanmar', 'phone_code': '+95'},
    {'code': 'MN', 'name': 'Mongolia', 'phone_code': '+976'},
    {'code': 'MO', 'name': 'Macao', 'phone_code': '+853'},
    {'code': 'MP', 'name': 'Northern Mariana Islands', 'phone_code': '+1'},
    {'code': 'MQ', 'name': 'Martinique', 'phone_code': '+596'},
    {'code': 'MR', 'name': 'Mauritania', 'phone_code': '+222'},
    {'code': 'MS', 'name': 'Montserrat', 'phone_code': '+1'},
    {'code': 'MT', 'name': 'Malta', 'phone_code': '+356'},
    {'code': 'MU', 'name': 'Mauritius', 'phone_code': '+230'},
    {'code': 'MV', 'name': 'Maldives', 'phone_code': '+960'},
    {'code': 'MW', 'name': 'Malawi', 'phone_code': '+265'},
    {'code': 'MX', 'name': 'Mexico', 'phone_code': '+52'},
    {'code': 'MY', 'name': 'Malaysia', 'phone_code': '+60'},
    {'code': 'MZ', 'name': 'Mozambique', 'phone_code': '+258'},
    {'code': 'NA', 'name': 'Namibia', 'phone_code': '+264'},
    {'code': 'NC', 'name': 'New Caledonia', 'phone_code': '+687'},
    {'code': 'NE', 'name': 'Niger', 'phone_code': '+227'},
    {'code': 'NF', 'name': 'Norfolk Island', 'phone_code': '+672'},
    {'code': 'NG', 'name': 'Nigeria', 'phone_code': '+234'},
    {'code': 'NI', 'name': 'Nicaragua', 'phone_code': '+505'},
    {'code': 'NL', 'name': 'Netherlands', 'phone_code': '+31'},
    {'code': 'NO', 'name': 'Norway', 'phone_code': '+47'},
    {'code': 'NP', 'name': 'Nepal', 'phone_code': '+977'},
    {'code': 'NR', 'name': 'Nauru', 'phone_code': '+674'},
    {'code': 'NU', 'name': 'Niue', 'phone_code': '+683'},
    {'code': 'NZ', 'name': 'New Zealand', 'phone_code': '+64'},
    {'code': 'OM', 'name': 'Oman', 'phone_code': '+968'},
    {'code': 'PA', 'name': 'Panama', 'phone_code': '+507'},
    {'code': 'PE', 'name': 'Peru', 'phone_code': '+51'},
    {'code': 'PF', 'name': 'French Polynesia', 'phone_code': '+689'},
    {'code': 'PG', 'name': 'Papua New Guinea', 'phone_code': '+675'},
    {'code': 'PH', 'name': 'Philippines', 'phone_code': '+63'},
    {'code': 'PK', 'name': 'Pakistan', 'phone_code': '+92'},
    {'code': 'PL', 'name': 'Poland', 'phone_code': '+48'},
    {'code': 'PM', 'name': 'Saint Pierre and Miquelon', 'phone_code': '+508'},
    {'code': 'PN', 'name': 'Pitcairn', 'phone_code': '+64'},
    {'code': 'PR', 'name': 'Puerto Rico', 'phone_code': '+1'},
    {'code': 'PS', 'name': 'Palestine', 'phone_code': '+970'},
    {'code': 'PT', 'name': 'Portugal', 'phone_code': '+351'},
    {'code': 'PW', 'name': 'Palau', 'phone_code': '+680'},
    {'code': 'PY', 'name': 'Paraguay', 'phone_code': '+595'},
    {'code': 'QA', 'name': 'Qatar', 'phone_code': '+974'},
    {'code': 'RE', 'name': 'Réunion', 'phone_code': '+262'},
    {'code': 'RO', 'name': 'Romania', 'phone_code': '+40'},
    {'code': 'RS', 'name': 'Serbia', 'phone_code': '+381'},
    {'code': 'RU', 'name': 'Russia', 'phone_code': '+7'},
    {'code': 'RW', 'name': 'Rwanda', 'phone_code': '+250'},
    {'code': 'SA', 'name': 'Saudi Arabia', 'phone_code': '+966'},
    {'code': 'SB', 'name': 'Solomon Islands', 'phone_code': '+677'},
    {'code': 'SC', 'name': 'Seychelles', 'phone_code': '+248'},
    {'code': 'SD', 'name': 'Sudan', 'phone_code': '+249'},
    {'code': 'SE', 'name': 'Sweden', 'phone_code': '+46'},
    {'code': 'SG', 'name': 'Singapore', 'phone_code': '+65'},
    {'code': 'SH', 'name': 'Saint Helena', 'phone_code': '+290'},
    {'code': 'SI', 'name': 'Slovenia', 'phone_code': '+386'},
    {'code': 'SJ', 'name': 'Svalbard and Jan Mayen', 'phone_code': '+47'},
    {'code': 'SK', 'name': 'Slovakia', 'phone_code': '+421'},
    {'code': 'SL', 'name': 'Sierra Leone', 'phone_code': '+232'},
    {'code': 'SM', 'name': 'San Marino', 'phone_code': '+378'},
    {'code': 'SN', 'name': 'Senegal', 'phone_code': '+221'},
    {'code': 'SO', 'name': 'Somalia', 'phone_code': '+252'},
    {'code': 'SR', 'name': 'Suriname', 'phone_code': '+597'},
    {'code': 'SS', 'name': 'South Sudan', 'phone_code': '+211'},
    {'code': 'ST', 'name': 'São Tomé and Príncipe', 'phone_code': '+239'},
    {'code': 'SV', 'name': 'El Salvador', 'phone_code': '+503'},
    {'code': 'SX', 'name': 'Sint Maarten', 'phone_code': '+1'},
    {'code': 'SY', 'name': 'Syria', 'phone_code': '+963'},
    {'code': 'SZ', 'name': 'Eswatini', 'phone_code': '+268'},
    {'code': 'TC', 'name': 'Turks and Caicos Islands', 'phone_code': '+1'},
    {'code': 'TD', 'name': 'Chad', 'phone_code': '+235'},
    {'code': 'TF', 'name': 'French Southern Territories', 'phone_code': '+262'},
    {'code': 'TG', 'name': 'Togo', 'phone_code': '+228'},
    {'code': 'TH', 'name': 'Thailand', 'phone_code': '+66'},
    {'code': 'TJ', 'name': 'Tajikistan', 'phone_code': '+992'},
    {'code': 'TK', 'name': 'Tokelau', 'phone_code': '+690'},
    {'code': 'TL', 'name': 'Timor-Leste', 'phone_code': '+670'},
    {'code': 'TM', 'name': 'Turkmenistan', 'phone_code': '+993'},
    {'code': 'TN', 'name': 'Tunisia', 'phone_code': '+216'},
    {'code': 'TO', 'name': 'Tonga', 'phone_code': '+676'},
    {'code': 'TR', 'name': 'Turkey', 'phone_code': '+90'},
    {'code': 'TT', 'name': 'Trinidad and Tobago', 'phone_code': '+1'},
    {'code': 'TV', 'name': 'Tuvalu', 'phone_code': '+688'},
    {'code': 'TW', 'name': 'Taiwan', 'phone_code': '+886'},
    {'code': 'TZ', 'name': 'Tanzania', 'phone_code': '+255'},
    {'code': 'UA', 'name': 'Ukraine', 'phone_code': '+380'},
    {'code': 'UG', 'name': 'Uganda', 'phone_code': '+256'},
    {'code': 'UM', 'name': 'United States Minor Outlying Islands', 'phone_code': '+1'},
    {'code': 'US', 'name': 'United States', 'phone_code': '+1'},
    {'code': 'UY', 'name': 'Uruguay', 'phone_code': '+598'},
    {'code': 'UZ', 'name': 'Uzbekistan', 'phone_code': '+998'},
    {'code': 'VA', 'name': 'Vatican City', 'phone_code': '+39'},
    {'code': 'VC', 'name': 'Saint Vincent and the Grenadines', 'phone_code': '+1'},
    {'code': 'VE', 'name': 'Venezuela', 'phone_code': '+58'},
    {'code': 'VG', 'name': 'British Virgin Islands', 'phone_code': '+1'},
    {'code': 'VI', 'name': 'U.S. Virgin Islands', 'phone_code': '+1'},
    {'code': 'VN', 'name': 'Vietnam', 'phone_code': '+84'},
    {'code': 'VU', 'name': 'Vanuatu', 'phone_code': '+678'},
    {'code': 'WF', 'name': 'Wallis and Futuna', 'phone_code': '+681'},
    {'code': 'WS', 'name': 'Samoa', 'phone_code': '+685'},
    {'code': 'YE', 'name': 'Yemen', 'phone_code': '+967'},
    {'code': 'YT', 'name': 'Mayotte', 'phone_code': '+262'},
    {'code': 'ZA', 'name': 'South Africa', 'phone_code': '+27'},
    {'code': 'ZM', 'name': 'Zambia', 'phone_code': '+260'},
    {'code': 'ZW', 'name': 'Zimbabwe', 'phone_code': '+263'},
    {'code': 'AE', 'name': 'United Arab Emirates', 'phone_code': '+971'},
    {'code': 'AF', 'name': 'Afghanistan', 'phone_code': '+93'},
    {'code': 'AG', 'name': 'Antigua and Barbuda', 'phone_code': '+1'},
    {'code': 'AI', 'name': 'Anguilla', 'phone_code': '+1'},
    {'code': 'AL', 'name': 'Albania', 'phone_code': '+355'},
    {'code': 'AM', 'name': 'Armenia', 'phone_code': '+374'},
    {'code': 'AO', 'name': 'Angola', 'phone_code': '+244'},
    {'code': 'AQ', 'name': 'Antarctica', 'phone_code': '+672'},
    {'code': 'AR', 'name': 'Argentina', 'phone_code': '+54'},
    {'code': 'AS', 'name': 'American Samoa', 'phone_code': '+1'},
    {'code': 'AT', 'name': 'Austria', 'phone_code': '+43'},
    {'code': 'AU', 'name': 'Australia', 'phone_code': '+61'},
    {'code': 'AW', 'name': 'Aruba', 'phone_code': '+297'},
    {'code': 'AX', 'name': 'Åland Islands', 'phone_code': '+358'},
    {'code': 'AZ', 'name': 'Azerbaijan', 'phone_code': '+994'},
    {'code': 'BA', 'name': 'Bosnia and Herzegovina', 'phone_code': '+387'},
    {'code': 'BB', 'name': 'Barbados', 'phone_code': '+1'},
    {'code': 'BD', 'name': 'Bangladesh', 'phone_code': '+880'},
    {'code': 'BE', 'name': 'Belgium', 'phone_code': '+32'},
    {'code': 'BF', 'name': 'Burkina Faso', 'phone_code': '+226'},
    {'code': 'BG', 'name': 'Bulgaria', 'phone_code': '+359'},
    {'code': 'BH', 'name': 'Bahrain', 'phone_code': '+973'},
    {'code': 'BI', 'name': 'Burundi', 'phone_code': '+257'},
    {'code': 'BJ', 'name': 'Benin', 'phone_code': '+229'},
    {'code': 'BL', 'name': 'Saint Barthélemy', 'phone_code': '+590'},
    {'code': 'BM', 'name': 'Bermuda', 'phone_code': '+1'},
    {'code': 'BN', 'name': 'Brunei', 'phone_code': '+673'},
    {'code': 'BO', 'name': 'Bolivia', 'phone_code': '+591'},
    {'code': 'BQ', 'name': 'Caribbean Netherlands', 'phone_code': '+599'},
    {'code': 'BR', 'name': 'Brazil', 'phone_code': '+55'},
    {'code': 'BS', 'name': 'Bahamas', 'phone_code': '+1'},
    {'code': 'BT', 'name': 'Bhutan', 'phone_code': '+975'},
    {'code': 'BV', 'name': 'Bouvet Island', 'phone_code': '+47'},
    {'code': 'BW', 'name': 'Botswana', 'phone_code': '+267'},
    {'code': 'BY', 'name': 'Belarus', 'phone_code': '+375'},
    {'code': 'BZ', 'name': 'Belize', 'phone_code': '+501'},
    {'code': 'CA', 'name': 'Canada', 'phone_code': '+1'},
    {'code': 'CC', 'name': 'Cocos (Keeling) Islands', 'phone_code': '+61'},
    {'code': 'CD', 'name': 'Democratic Republic of the Congo', 'phone_code': '+243'},
    {'code': 'CF', 'name': 'Central African Republic', 'phone_code': '+236'},
    {'code': 'CG', 'name': 'Republic of the Congo', 'phone_code': '+242'},
    {'code': 'CH', 'name': 'Switzerland', 'phone_code': '+41'},
    {'code': 'CI', 'name': 'Côte d\'Ivoire', 'phone_code': '+225'},
    {'code': 'CK', 'name': 'Cook Islands', 'phone_code': '+682'},
    {'code': 'CL', 'name': 'Chile', 'phone_code': '+56'},
    {'code': 'CM', 'name': 'Cameroon', 'phone_code': '+237'},
    {'code': 'CN', 'name': 'China', 'phone_code': '+86'},
    {'code': 'CO', 'name': 'Colombia', 'phone_code': '+57'},
    {'code': 'CR', 'name': 'Costa Rica', 'phone_code': '+506'},
    {'code': 'CU', 'name': 'Cuba', 'phone_code': '+53'},
    {'code': 'CV', 'name': 'Cape Verde', 'phone_code': '+238'},
    {'code': 'CW', 'name': 'Curaçao', 'phone_code': '+599'},
    {'code': 'CX', 'name': 'Christmas Island', 'phone_code': '+61'},
    {'code': 'CY', 'name': 'Cyprus', 'phone_code': '+357'},
    {'code': 'CZ', 'name': 'Czech Republic', 'phone_code': '+420'},
    {'code': 'DE', 'name': 'Germany', 'phone_code': '+49'},
    {'code': 'DJ', 'name': 'Djibouti', 'phone_code': '+253'},
    {'code': 'DK', 'name': 'Denmark', 'phone_code': '+45'},
    {'code': 'DM', 'name': 'Dominica', 'phone_code': '+1'},
    {'code': 'DO', 'name': 'Dominican Republic', 'phone_code': '+1'},
    {'code': 'DZ', 'name': 'Algeria', 'phone_code': '+213'},
    {'code': 'EC', 'name': 'Ecuador', 'phone_code': '+593'},
    {'code': 'EE', 'name': 'Estonia', 'phone_code': '+372'},
    {'code': 'EG', 'name': 'Egypt', 'phone_code': '+20'},
    {'code': 'EH', 'name': 'Western Sahara', 'phone_code': '+212'},
    {'code': 'ER', 'name': 'Eritrea', 'phone_code': '+291'},
    {'code': 'ES', 'name': 'Spain', 'phone_code': '+34'},
    {'code': 'ET', 'name': 'Ethiopia', 'phone_code': '+251'},
    {'code': 'FI', 'name': 'Finland', 'phone_code': '+358'},
    {'code': 'FJ', 'name': 'Fiji', 'phone_code': '+679'},
    {'code': 'FK', 'name': 'Falkland Islands', 'phone_code': '+500'},
    {'code': 'FM', 'name': 'Micronesia', 'phone_code': '+691'},
    {'code': 'FO', 'name': 'Faroe Islands', 'phone_code': '+298'},
    {'code': 'FR', 'name': 'France', 'phone_code': '+33'},
    {'code': 'GA', 'name': 'Gabon', 'phone_code': '+241'},
    {'code': 'GB', 'name': 'United Kingdom', 'phone_code': '+44'},
    {'code': 'GD', 'name': 'Grenada', 'phone_code': '+1'},
    {'code': 'GE', 'name': 'Georgia', 'phone_code': '+995'},
    {'code': 'GF', 'name': 'French Guiana', 'phone_code': '+594'},
    {'code': 'GG', 'name': 'Guernsey', 'phone_code': '+44'},
    {'code': 'GH', 'name': 'Ghana', 'phone_code': '+233'},
    {'code': 'GI', 'name': 'Gibraltar', 'phone_code': '+350'},
    {'code': 'GL', 'name': 'Greenland', 'phone_code': '+299'},
    {'code': 'GM', 'name': 'Gambia', 'phone_code': '+220'},
    {'code': 'GN', 'name': 'Guinea', 'phone_code': '+224'},
    {'code': 'GP', 'name': 'Guadeloupe', 'phone_code': '+590'},
    {'code': 'GQ', 'name': 'Equatorial Guinea', 'phone_code': '+240'},
    {'code': 'GR', 'name': 'Greece', 'phone_code': '+30'},
    {'code': 'GS', 'name': 'South Georgia and the South Sandwich Islands', 'phone_code': '+500'},
    {'code': 'GT', 'name': 'Guatemala', 'phone_code': '+502'},
    {'code': 'GU', 'name': 'Guam', 'phone_code': '+1'},
    {'code': 'GW', 'name': 'Guinea-Bissau', 'phone_code': '+245'},
    {'code': 'GY', 'name': 'Guyana', 'phone_code': '+592'},
    {'code': 'HK', 'name': 'Hong Kong', 'phone_code': '+852'},
    {'code': 'HM', 'name': 'Heard Island and McDonald Islands', 'phone_code': '+672'},
    {'code': 'HN', 'name': 'Honduras', 'phone_code': '+504'},
    {'code': 'HR', 'name': 'Croatia', 'phone_code': '+385'},
    {'code': 'HT', 'name': 'Haiti', 'phone_code': '+509'},
    {'code': 'HU', 'name': 'Hungary', 'phone_code': '+36'},

    {'code': 'ID', 'name': 'Indonesia', 'phone_code': '+62'},
    {'code': 'IE', 'name': 'Ireland', 'phone_code': '+353'},
    {'code': 'IL', 'name': 'Israel', 'phone_code': '+972'},
    {'code': 'IM', 'name': 'Isle of Man', 'phone_code': '+44'},
    {'code': 'IN', 'name': 'India', 'phone_code': '+91'},
    {'code': 'IO', 'name': 'British Indian Ocean Territory', 'phone_code': '+246'},
    {'code': 'IQ', 'name': 'Iraq', 'phone_code': '+964'},
    {'code': 'IR', 'name': 'Iran', 'phone_code': '+98'},
    {'code': 'IS', 'name': 'Iceland', 'phone_code': '+354'},
    {'code': 'IT', 'name': 'Italy', 'phone_code': '+39'},
    {'code': 'JE', 'name': 'Jersey', 'phone_code': '+44'},
    {'code': 'JM', 'name': 'Jamaica', 'phone_code': '+1'},
    {'code': 'JO', 'name': 'Jordan', 'phone_code': '+962'},
    {'code': 'JP', 'name': 'Japan', 'phone_code': '+81'},
    {'code': 'KE', 'name': 'Kenya', 'phone_code': '+254'},
    {'code': 'KG', 'name': 'Kyrgyzstan', 'phone_code': '+996'},
    {'code': 'KH', 'name': 'Cambodia', 'phone_code': '+855'},
    {'code': 'KI', 'name': 'Kiribati', 'phone_code': '+686'},
    {'code': 'KM', 'name': 'Comoros', 'phone_code': '+269'},
    {'code': 'KN', 'name': 'Saint Kitts and Nevis', 'phone_code': '+1'},
    {'code': 'KP', 'name': 'North Korea', 'phone_code': '+850'},
    {'code': 'KR', 'name': 'South Korea', 'phone_code': '+82'},
    {'code': 'KW', 'name': 'Kuwait', 'phone_code': '+965'},
    {'code': 'KY', 'name': 'Cayman Islands', 'phone_code': '+1'},
    {'code': 'KZ', 'name': 'Kazakhstan', 'phone_code': '+7'},
    {'code': 'LA', 'name': 'Laos', 'phone_code': '+856'},
    {'code': 'LB', 'name': 'Lebanon', 'phone_code': '+961'},
    {'code': 'LC', 'name': 'Saint Lucia', 'phone_code': '+1'},
    {'code': 'LI', 'name': 'Liechtenstein', 'phone_code': '+423'},
    {'code': 'LK', 'name': 'Sri Lanka', 'phone_code': '+94'},
    {'code': 'LR', 'name': 'Liberia', 'phone_code': '+231'},
    {'code': 'LS', 'name': 'Lesotho', 'phone_code': '+266'},
    {'code': 'LT', 'name': 'Lithuania', 'phone_code': '+370'},
    {'code': 'LU', 'name': 'Luxembourg', 'phone_code': '+352'},
    {'code': 'LV', 'name': 'Latvia', 'phone_code': '+371'},
    {'code': 'LY', 'name': 'Libya', 'phone_code': '+218'},
    {'code': 'MA', 'name': 'Morocco', 'phone_code': '+212'},
    {'code': 'MC', 'name': 'Monaco', 'phone_code': '+377'},
    {'code': 'MD', 'name': 'Moldova', 'phone_code': '+373'},
    {'code': 'ME', 'name': 'Montenegro', 'phone_code': '+382'},
    {'code': 'MF', 'name': 'Saint Martin', 'phone_code': '+590'},
    {'code': 'MG', 'name': 'Madagascar', 'phone_code': '+261'},
    {'code': 'MH', 'name': 'Marshall Islands', 'phone_code': '+692'},
    {'code': 'MK', 'name': 'North Macedonia', 'phone_code': '+389'},
    {'code': 'ML', 'name': 'Mali', 'phone_code': '+223'},
    {'code': 'MM', 'name': 'Myanmar', 'phone_code': '+95'},
    {'code': 'MN', 'name': 'Mongolia', 'phone_code': '+976'},
    {'code': 'MO', 'name': 'Macao', 'phone_code': '+853'},
    {'code': 'MP', 'name': 'Northern Mariana Islands', 'phone_code': '+1'},
    {'code': 'MQ', 'name': 'Martinique', 'phone_code': '+596'},
    {'code': 'MR', 'name': 'Mauritania', 'phone_code': '+222'},
    {'code': 'MS', 'name': 'Montserrat', 'phone_code': '+1'},
    {'code': 'MT', 'name': 'Malta', 'phone_code': '+356'},
    {'code': 'MU', 'name': 'Mauritius', 'phone_code': '+230'},
    {'code': 'MV', 'name': 'Maldives', 'phone_code': '+960'},
    {'code': 'MW', 'name': 'Malawi', 'phone_code': '+265'},
    {'code': 'MX', 'name': 'Mexico', 'phone_code': '+52'},
    {'code': 'MY', 'name': 'Malaysia', 'phone_code': '+60'},
    {'code': 'MZ', 'name': 'Mozambique', 'phone_code': '+258'},
    {'code': 'NA', 'name': 'Namibia', 'phone_code': '+264'},
    {'code': 'NC', 'name': 'New Caledonia', 'phone_code': '+687'},
    {'code': 'NE', 'name': 'Niger', 'phone_code': '+227'},
    {'code': 'NF', 'name': 'Norfolk Island', 'phone_code': '+672'},
    {'code': 'NG', 'name': 'Nigeria', 'phone_code': '+234'},
    {'code': 'NI', 'name': 'Nicaragua', 'phone_code': '+505'},
    {'code': 'NL', 'name': 'Netherlands', 'phone_code': '+31'},
    {'code': 'NO', 'name': 'Norway', 'phone_code': '+47'},
    {'code': 'NP', 'name': 'Nepal', 'phone_code': '+977'},
    {'code': 'NR', 'name': 'Nauru', 'phone_code': '+674'},
    {'code': 'NU', 'name': 'Niue', 'phone_code': '+683'},
    {'code': 'NZ', 'name': 'New Zealand', 'phone_code': '+64'},
    {'code': 'OM', 'name': 'Oman', 'phone_code': '+968'},
    {'code': 'PA', 'name': 'Panama', 'phone_code': '+507'},
    {'code': 'PE', 'name': 'Peru', 'phone_code': '+51'},
    {'code': 'PF', 'name': 'French Polynesia', 'phone_code': '+689'},
    {'code': 'PG', 'name': 'Papua New Guinea', 'phone_code': '+675'},
    {'code': 'PH', 'name': 'Philippines', 'phone_code': '+63'},
    {'code': 'PK', 'name': 'Pakistan', 'phone_code': '+92'},
    {'code': 'PL', 'name': 'Poland', 'phone_code': '+48'},
    {'code': 'PM', 'name': 'Saint Pierre and Miquelon', 'phone_code': '+508'},
    {'code': 'PN', 'name': 'Pitcairn', 'phone_code': '+64'},
    {'code': 'PR', 'name': 'Puerto Rico', 'phone_code': '+1'},
    {'code': 'PS', 'name': 'Palestine', 'phone_code': '+970'},
    {'code': 'PT', 'name': 'Portugal', 'phone_code': '+351'},
    {'code': 'PW', 'name': 'Palau', 'phone_code': '+680'},
    {'code': 'PY', 'name': 'Paraguay', 'phone_code': '+595'},
    {'code': 'QA', 'name': 'Qatar', 'phone_code': '+974'},
    {'code': 'RE', 'name': 'Réunion', 'phone_code': '+262'},
    {'code': 'RO', 'name': 'Romania', 'phone_code': '+40'},
    {'code': 'RS', 'name': 'Serbia', 'phone_code': '+381'},
    {'code': 'RU', 'name': 'Russia', 'phone_code': '+7'},
    {'code': 'RW', 'name': 'Rwanda', 'phone_code': '+250'},
    {'code': 'SA', 'name': 'Saudi Arabia', 'phone_code': '+966'},
    {'code': 'SB', 'name': 'Solomon Islands', 'phone_code': '+677'},
    {'code': 'SC', 'name': 'Seychelles', 'phone_code': '+248'},
    {'code': 'SD', 'name': 'Sudan', 'phone_code': '+249'},
    {'code': 'SE', 'name': 'Sweden', 'phone_code': '+46'},
    {'code': 'SG', 'name': 'Singapore', 'phone_code': '+65'},
    {'code': 'SH', 'name': 'Saint Helena', 'phone_code': '+290'},
    {'code': 'SI', 'name': 'Slovenia', 'phone_code': '+386'},
    {'code': 'SJ', 'name': 'Svalbard and Jan Mayen', 'phone_code': '+47'},
    {'code': 'SK', 'name': 'Slovakia', 'phone_code': '+421'},
    {'code': 'SL', 'name': 'Sierra Leone', 'phone_code': '+232'},
    {'code': 'SM', 'name': 'San Marino', 'phone_code': '+378'},
    {'code': 'SN', 'name': 'Senegal', 'phone_code': '+221'},
    {'code': 'SO', 'name': 'Somalia', 'phone_code': '+252'},
    {'code': 'SR', 'name': 'Suriname', 'phone_code': '+597'},
    {'code': 'SS', 'name': 'South Sudan', 'phone_code': '+211'},
    {'code': 'ST', 'name': 'São Tomé and Príncipe', 'phone_code': '+239'},
    {'code': 'SV', 'name': 'El Salvador', 'phone_code': '+503'},
    {'code': 'SX', 'name': 'Sint Maarten', 'phone_code': '+1'},
    {'code': 'SY', 'name': 'Syria', 'phone_code': '+963'},
    {'code': 'SZ', 'name': 'Eswatini', 'phone_code': '+268'},
    {'code': 'TC', 'name': 'Turks and Caicos Islands', 'phone_code': '+1'},
    {'code': 'TD', 'name': 'Chad', 'phone_code': '+235'},
    {'code': 'TF', 'name': 'French Southern Territories', 'phone_code': '+262'},
    {'code': 'TG', 'name': 'Togo', 'phone_code': '+228'},
    {'code': 'TH', 'name': 'Thailand', 'phone_code': '+66'},
    {'code': 'TJ', 'name': 'Tajikistan', 'phone_code': '+992'},
    {'code': 'TK', 'name': 'Tokelau', 'phone_code': '+690'},
    {'code': 'TL', 'name': 'Timor-Leste', 'phone_code': '+670'},
    {'code': 'TM', 'name': 'Turkmenistan', 'phone_code': '+993'},
    {'code': 'TN', 'name': 'Tunisia', 'phone_code': '+216'},
    {'code': 'TO', 'name': 'Tonga', 'phone_code': '+676'},
    {'code': 'TR', 'name': 'Turkey', 'phone_code': '+90'},
    {'code': 'TT', 'name': 'Trinidad and Tobago', 'phone_code': '+1'},
    {'code': 'TV', 'name': 'Tuvalu', 'phone_code': '+688'},
    {'code': 'TW', 'name': 'Taiwan', 'phone_code': '+886'},
    {'code': 'TZ', 'name': 'Tanzania', 'phone_code': '+255'},
    {'code': 'UA', 'name': 'Ukraine', 'phone_code': '+380'},
    {'code': 'UG', 'name': 'Uganda', 'phone_code': '+256'},
    {'code': 'UM', 'name': 'United States Minor Outlying Islands', 'phone_code': '+1'},
    {'code': 'US', 'name': 'United States', 'phone_code': '+1'},
    {'code': 'UY', 'name': 'Uruguay', 'phone_code': '+598'},
    {'code': 'UZ', 'name': 'Uzbekistan', 'phone_code': '+998'},
    {'code': 'VA', 'name': 'Vatican City', 'phone_code': '+39'},
    {'code': 'VC', 'name': 'Saint Vincent and the Grenadines', 'phone_code': '+1'},
    {'code': 'VE', 'name': 'Venezuela', 'phone_code': '+58'},
    {'code': 'VG', 'name': 'British Virgin Islands', 'phone_code': '+1'},
    {'code': 'VI', 'name': 'U.S. Virgin Islands', 'phone_code': '+1'},
    {'code': 'VN', 'name': 'Vietnam', 'phone_code': '+84'},
    {'code': 'VU', 'name': 'Vanuatu', 'phone_code': '+678'},
    {'code': 'WF', 'name': 'Wallis and Futuna', 'phone_code': '+681'},
    {'code': 'WS', 'name': 'Samoa', 'phone_code': '+685'},
    {'code': 'YE', 'name': 'Yemen', 'phone_code': '+967'},
    {'code': 'YT', 'name': 'Mayotte', 'phone_code': '+262'},
    {'code': 'ZA', 'name': 'South Africa', 'phone_code': '+27'},
    {'code': 'ZM', 'name': 'Zambia', 'phone_code': '+260'},
    {'code': 'ZW', 'name': 'Zimbabwe', 'phone_code': '+263'},
]

TIMEZONES = [
    {'code': 'UTC', 'name': 'Coordinated Universal Time', 'utc_offset': '+00:00'},
    {'code': 'GMT', 'name': 'Greenwich Mean Time', 'utc_offset': '+00:00'},

    # Americas
    {'code': 'America/New_York', 'name': 'Eastern Time (US & Canada)', 'utc_offset': '-05:00'},
    {'code': 'America/Chicago', 'name': 'Central Time (US & Canada)', 'utc_offset': '-06:00'},
    {'code': 'America/Denver', 'name': 'Mountain Time (US & Canada)', 'utc_offset': '-07:00'},
    {'code': 'America/Los_Angeles', 'name': 'Pacific Time (US & Canada)', 'utc_offset': '-08:00'},
    {'code': 'America/Anchorage', 'name': 'Alaska Time', 'utc_offset': '-09:00'},
    {'code': 'Pacific/Honolulu', 'name': 'Hawaii Time', 'utc_offset': '-10:00'},
    {'code': 'America/Toronto', 'name': 'Eastern Time (Canada)', 'utc_offset': '-05:00'},
    {'code': 'America/Vancouver', 'name': 'Pacific Time (Canada)', 'utc_offset': '-08:00'},
    {'code': 'America/Mexico_City', 'name': 'Mexico City Time', 'utc_offset': '-06:00'},
    {'code': 'America/Sao_Paulo', 'name': 'Brasília Time', 'utc_offset': '-03:00'},
    {'code': 'America/Argentina/Buenos_Aires', 'name': 'Argentina Time', 'utc_offset': '-03:00'},
    {'code': 'America/Santiago', 'name': 'Chile Time', 'utc_offset': '-03:00'},
    {'code': 'America/Bogota', 'name': 'Colombia Time', 'utc_offset': '-05:00'},
    {'code': 'America/Lima', 'name': 'Peru Time', 'utc_offset': '-05:00'},
    {'code': 'America/Caracas', 'name': 'Venezuela Time', 'utc_offset': '-04:00'},

    # Europe
    {'code': 'Europe/London', 'name': 'Greenwich Mean Time', 'utc_offset': '+00:00'},
    {'code': 'Europe/Dublin', 'name': 'Irish Standard Time', 'utc_offset': '+00:00'},
    {'code': 'Europe/Paris', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Berlin', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Rome', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Madrid', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Amsterdam', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Brussels', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Zurich', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Vienna', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Stockholm', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Oslo', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Copenhagen', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Helsinki', 'name': 'Eastern European Time', 'utc_offset': '+02:00'},
    {'code': 'Europe/Athens', 'name': 'Eastern European Time', 'utc_offset': '+02:00'},
    {'code': 'Europe/Istanbul', 'name': 'Turkey Time', 'utc_offset': '+03:00'},
    {'code': 'Europe/Moscow', 'name': 'Moscow Time', 'utc_offset': '+03:00'},
    {'code': 'Europe/Warsaw', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Prague', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Budapest', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Europe/Bucharest', 'name': 'Eastern European Time', 'utc_offset': '+02:00'},

    # Asia
    {'code': 'Asia/Dubai', 'name': 'Gulf Standard Time', 'utc_offset': '+04:00'},
    {'code': 'Asia/Riyadh', 'name': 'Arabia Standard Time', 'utc_offset': '+03:00'},
    {'code': 'Asia/Kuwait', 'name': 'Arabia Standard Time', 'utc_offset': '+03:00'},
    {'code': 'Asia/Qatar', 'name': 'Arabia Standard Time', 'utc_offset': '+03:00'},
    {'code': 'Asia/Bahrain', 'name': 'Arabia Standard Time', 'utc_offset': '+03:00'},
    {'code': 'Asia/Kolkata', 'name': 'India Standard Time', 'utc_offset': '+05:30'},
    {'code': 'Asia/Mumbai', 'name': 'India Standard Time', 'utc_offset': '+05:30'},
    {'code': 'Asia/Delhi', 'name': 'India Standard Time', 'utc_offset': '+05:30'},
    {'code': 'Asia/Karachi', 'name': 'Pakistan Standard Time', 'utc_offset': '+05:00'},
    {'code': 'Asia/Dhaka', 'name': 'Bangladesh Standard Time', 'utc_offset': '+06:00'},
    {'code': 'Asia/Colombo', 'name': 'Sri Lanka Standard Time', 'utc_offset': '+05:30'},
    {'code': 'Asia/Kathmandu', 'name': 'Nepal Time', 'utc_offset': '+05:45'},
    {'code': 'Asia/Kabul', 'name': 'Afghanistan Time', 'utc_offset': '+04:30'},
    {'code': 'Asia/Tehran', 'name': 'Iran Standard Time', 'utc_offset': '+03:30'},
    {'code': 'Asia/Baghdad', 'name': 'Arabia Standard Time', 'utc_offset': '+03:00'},
    {'code': 'Asia/Jerusalem', 'name': 'Israel Standard Time', 'utc_offset': '+02:00'},
    {'code': 'Asia/Beirut', 'name': 'Eastern European Time', 'utc_offset': '+02:00'},
    {'code': 'Asia/Damascus', 'name': 'Eastern European Time', 'utc_offset': '+02:00'},
    {'code': 'Asia/Amman', 'name': 'Eastern European Time', 'utc_offset': '+02:00'},
    {'code': 'Asia/Tokyo', 'name': 'Japan Standard Time', 'utc_offset': '+09:00'},
    {'code': 'Asia/Seoul', 'name': 'Korea Standard Time', 'utc_offset': '+09:00'},
    {'code': 'Asia/Shanghai', 'name': 'China Standard Time', 'utc_offset': '+08:00'},
    {'code': 'Asia/Beijing', 'name': 'China Standard Time', 'utc_offset': '+08:00'},
    {'code': 'Asia/Hong_Kong', 'name': 'Hong Kong Time', 'utc_offset': '+08:00'},
    {'code': 'Asia/Taipei', 'name': 'Taipei Time', 'utc_offset': '+08:00'},
    {'code': 'Asia/Singapore', 'name': 'Singapore Standard Time', 'utc_offset': '+08:00'},
    {'code': 'Asia/Kuala_Lumpur', 'name': 'Malaysia Time', 'utc_offset': '+08:00'},
    {'code': 'Asia/Bangkok', 'name': 'Indochina Time', 'utc_offset': '+07:00'},
    {'code': 'Asia/Ho_Chi_Minh', 'name': 'Indochina Time', 'utc_offset': '+07:00'},
    {'code': 'Asia/Jakarta', 'name': 'Western Indonesia Time', 'utc_offset': '+07:00'},
    {'code': 'Asia/Manila', 'name': 'Philippine Time', 'utc_offset': '+08:00'},
    {'code': 'Asia/Yangon', 'name': 'Myanmar Time', 'utc_offset': '+06:30'},
    {'code': 'Asia/Phnom_Penh', 'name': 'Indochina Time', 'utc_offset': '+07:00'},
    {'code': 'Asia/Vientiane', 'name': 'Indochina Time', 'utc_offset': '+07:00'},
    {'code': 'Asia/Almaty', 'name': 'Almaty Time', 'utc_offset': '+06:00'},
    {'code': 'Asia/Tashkent', 'name': 'Uzbekistan Time', 'utc_offset': '+05:00'},
    {'code': 'Asia/Bishkek', 'name': 'Kyrgyzstan Time', 'utc_offset': '+06:00'},
    {'code': 'Asia/Dushanbe', 'name': 'Tajikistan Time', 'utc_offset': '+05:00'},
    {'code': 'Asia/Ashgabat', 'name': 'Turkmenistan Time', 'utc_offset': '+05:00'},
    {'code': 'Asia/Baku', 'name': 'Azerbaijan Time', 'utc_offset': '+04:00'},
    {'code': 'Asia/Yerevan', 'name': 'Armenia Time', 'utc_offset': '+04:00'},
    {'code': 'Asia/Tbilisi', 'name': 'Georgia Time', 'utc_offset': '+04:00'},
    {'code': 'Asia/Ulaanbaatar', 'name': 'Mongolia Time', 'utc_offset': '+08:00'},

    # Africa
    {'code': 'Africa/Cairo', 'name': 'Eastern European Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Lagos', 'name': 'West Africa Time', 'utc_offset': '+01:00'},
    {'code': 'Africa/Nairobi', 'name': 'East Africa Time', 'utc_offset': '+03:00'},
    {'code': 'Africa/Johannesburg', 'name': 'South Africa Standard Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Cape_Town', 'name': 'South Africa Standard Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Casablanca', 'name': 'Western European Time', 'utc_offset': '+00:00'},
    {'code': 'Africa/Tunis', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Africa/Algiers', 'name': 'Central European Time', 'utc_offset': '+01:00'},
    {'code': 'Africa/Tripoli', 'name': 'Eastern European Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Khartoum', 'name': 'Central Africa Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Addis_Ababa', 'name': 'East Africa Time', 'utc_offset': '+03:00'},
    {'code': 'Africa/Dar_es_Salaam', 'name': 'East Africa Time', 'utc_offset': '+03:00'},
    {'code': 'Africa/Kampala', 'name': 'East Africa Time', 'utc_offset': '+03:00'},
    {'code': 'Africa/Kigali', 'name': 'Central Africa Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Lusaka', 'name': 'Central Africa Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Harare', 'name': 'Central Africa Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Gaborone', 'name': 'Central Africa Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Windhoek', 'name': 'West Africa Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Maputo', 'name': 'Central Africa Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Blantyre', 'name': 'Central Africa Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Lilongwe', 'name': 'Central Africa Time', 'utc_offset': '+02:00'},
    {'code': 'Africa/Accra', 'name': 'Greenwich Mean Time', 'utc_offset': '+00:00'},
    {'code': 'Africa/Abidjan', 'name': 'Greenwich Mean Time', 'utc_offset': '+00:00'},
    {'code': 'Africa/Dakar', 'name': 'Greenwich Mean Time', 'utc_offset': '+00:00'},
    {'code': 'Africa/Bamako', 'name': 'Greenwich Mean Time', 'utc_offset': '+00:00'},
    {'code': 'Africa/Conakry', 'name': 'Greenwich Mean Time', 'utc_offset': '+00:00'},
    {'code': 'Africa/Freetown', 'name': 'Greenwich Mean Time', 'utc_offset': '+00:00'},
    {'code': 'Africa/Monrovia', 'name': 'Greenwich Mean Time', 'utc_offset': '+00:00'},

    # Australia & Oceania
    {'code': 'Australia/Sydney', 'name': 'Australian Eastern Time', 'utc_offset': '+10:00'},
    {'code': 'Australia/Melbourne', 'name': 'Australian Eastern Time', 'utc_offset': '+10:00'},
    {'code': 'Australia/Brisbane', 'name': 'Australian Eastern Time', 'utc_offset': '+10:00'},
    {'code': 'Australia/Perth', 'name': 'Australian Western Time', 'utc_offset': '+08:00'},
    {'code': 'Australia/Adelaide', 'name': 'Australian Central Time', 'utc_offset': '+09:30'},
    {'code': 'Australia/Darwin', 'name': 'Australian Central Time', 'utc_offset': '+09:30'},
    {'code': 'Australia/Hobart', 'name': 'Australian Eastern Time', 'utc_offset': '+10:00'},
    {'code': 'Pacific/Auckland', 'name': 'New Zealand Standard Time', 'utc_offset': '+12:00'},
    {'code': 'Pacific/Fiji', 'name': 'Fiji Time', 'utc_offset': '+12:00'},
    {'code': 'Pacific/Guam', 'name': 'Chamorro Standard Time', 'utc_offset': '+10:00'},
    {'code': 'Pacific/Port_Moresby', 'name': 'Papua New Guinea Time', 'utc_offset': '+10:00'},
    {'code': 'Pacific/Noumea', 'name': 'New Caledonia Time', 'utc_offset': '+11:00'},
    {'code': 'Pacific/Apia', 'name': 'West Samoa Time', 'utc_offset': '+13:00'},
    {'code': 'Pacific/Tahiti', 'name': 'Tahiti Time', 'utc_offset': '-10:00'},
    {'code': 'Pacific/Marquesas', 'name': 'Marquesas Time', 'utc_offset': '-09:30'},
    {'code': 'Pacific/Easter', 'name': 'Easter Island Time', 'utc_offset': '-06:00'},
    {'code': 'Pacific/Galapagos', 'name': 'Galapagos Time', 'utc_offset': '-06:00'},

    # Atlantic
    {'code': 'Atlantic/Azores', 'name': 'Azores Time', 'utc_offset': '-01:00'},
    {'code': 'Atlantic/Cape_Verde', 'name': 'Cape Verde Time', 'utc_offset': '-01:00'},
    {'code': 'Atlantic/Canary', 'name': 'Western European Time', 'utc_offset': '+00:00'},
    {'code': 'Atlantic/Madeira', 'name': 'Western European Time', 'utc_offset': '+00:00'},
    {'code': 'Atlantic/Reykjavik', 'name': 'Greenwich Mean Time', 'utc_offset': '+00:00'},
    {'code': 'Atlantic/Faroe', 'name': 'Western European Time', 'utc_offset': '+00:00'},
    {'code': 'Atlantic/Bermuda', 'name': 'Atlantic Time', 'utc_offset': '-04:00'},
    {'code': 'Atlantic/Stanley', 'name': 'Falkland Islands Time', 'utc_offset': '-03:00'},

    # Indian Ocean
    {'code': 'Indian/Mauritius', 'name': 'Mauritius Time', 'utc_offset': '+04:00'},
    {'code': 'Indian/Maldives', 'name': 'Maldives Time', 'utc_offset': '+05:00'},
    {'code': 'Indian/Chagos', 'name': 'Indian Ocean Time', 'utc_offset': '+06:00'},
    {'code': 'Indian/Reunion', 'name': 'Réunion Time', 'utc_offset': '+04:00'},
    {'code': 'Indian/Mayotte', 'name': 'East Africa Time', 'utc_offset': '+03:00'},
    {'code': 'Indian/Comoro', 'name': 'East Africa Time', 'utc_offset': '+03:00'},
    {'code': 'Indian/Antananarivo', 'name': 'East Africa Time', 'utc_offset': '+03:00'},
    {'code': 'Indian/Kerguelen', 'name': 'French Southern Time', 'utc_offset': '+05:00'},
    {'code': 'Indian/Christmas', 'name': 'Christmas Island Time', 'utc_offset': '+07:00'},
    {'code': 'Indian/Cocos', 'name': 'Cocos Islands Time', 'utc_offset': '+06:30'},
]
