# Generated by Django 5.2.9 on 2025-12-05 19:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['level', 'name']},
        ),
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'due_date']},
        ),
        migrations.AddField(
            model_name='department',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual department budget', max_digits=15),
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='Department code', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='hrms.department'),
        ),
        migrations.AddField(
            model_name='designation',
            name='level',
            field=models.IntegerField(default=1, help_text='Hierarchy level 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='total_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('URGENT', 'URGENT')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='userprojectmapping',
            name='role',
            field=models.CharField(blank=True, help_text='Role in project', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='designation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('SICK', 'SICK'), ('CASUAL', 'CASUAL'), ('EARNED', 'EARNED'), ('MATERNITY', 'MATERNITY'), ('PATERNITY', 'PATERNITY'), ('UNPAID', 'UNPAID'), ('COMPASSIONATE', 'COMPASSIONATE'), ('STUDY', 'STUDY')], default='CASUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ON_HOLD', 'ON_HOLD'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks_hrms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('REVIEW', 'REVIEW'), ('DONE', 'DONE'), ('BLOCKED', 'BLOCKED')], default='TODO', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userprojectmapping',
            unique_together={('user', 'project')},
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id', models.CharField(help_text='Employee ID/Code', max_length=50, unique=True)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ON_LEAVE', 'ON_LEAVE'), ('SUSPENDED', 'SUSPENDED'), ('RESIGNED', 'RESIGNED'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'FULL_TIME'), ('PART_TIME', 'PART_TIME'), ('CONTRACT', 'CONTRACT'), ('INTERN', 'INTERN'), ('PROBATION', 'PROBATION')], default='FULL_TIME', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('id_number', models.CharField(blank=True, help_text='National ID/Passport', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly base salary', max_digits=12)),
                ('payment_frequency', models.CharField(choices=[('WEEKLY', 'WEEKLY'), ('BI_WEEKLY', 'BI_WEEKLY'), ('SEMI_MONTHLY', 'SEMI_MONTHLY'), ('MONTHLY', 'MONTHLY')], default='MONTHLY', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('annual_leave_balance', models.DecimalField(decimal_places=1, default=Decimal('14.0'), max_digits=5)),
                ('sick_leave_balance', models.DecimalField(decimal_places=1, default=Decimal('10.0'), max_digits=5)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrms.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrms.designation')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hrms.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_applications', to='hrms.employee'),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('APPROVED', 'APPROVED'), ('PROCESSING', 'PROCESSING'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('other_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('mpf_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Employee MPF contribution', max_digits=12)),
                ('mpf_employer', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Employer MPF contribution', max_digits=12)),
                ('insurance_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('working_days', models.IntegerField(default=0)),
                ('absent_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='hrms.employee')),
            ],
            options={
                'ordering': ['-period__year', '-period__month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], default='EARNING', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hrms.payroll')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='e.g., January 2024', max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('APPROVED', 'APPROVED'), ('PROCESSING', 'PROCESSING'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='hrms.payrollperiod'),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.IntegerField()),
                ('leave_type', models.CharField(choices=[('SICK', 'SICK'), ('CASUAL', 'CASUAL'), ('EARNED', 'EARNED'), ('MATERNITY', 'MATERNITY'), ('PATERNITY', 'PATERNITY'), ('UNPAID', 'UNPAID'), ('COMPASSIONATE', 'COMPASSIONATE'), ('STUDY', 'STUDY')], max_length=20)),
                ('entitled_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('carried_over', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hrms.employee')),
            ],
            options={
                'unique_together': {('employee', 'year', 'leave_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'period')},
        ),
    ]
