# Generated by Django migration
from django.db import migrations


def seed_subscription_plans(apps, schema_editor):
    """Seed the three subscription tiers: Free, Pro, and Pro+ Enterprise"""
    SubscriptionPlan = apps.get_model('users', 'SubscriptionPlan')
    
    # Free Plan
    SubscriptionPlan.objects.update_or_create(
        plan_type='free',
        defaults={
            'name': 'Free',
            'name_en': 'Free',
            'name_zh': '免費版',
            'description': 'Perfect for getting started with basic features.',
            'description_en': 'Perfect for getting started with basic features.',
            'description_zh': '適合剛開始使用基本功能的用戶。',
            # Pricing
            'price_monthly': 0,
            'price_yearly': 0,
            'currency': 'USD',
            # Limits
            'max_users': 1,
            'max_companies': 1,
            'max_storage_gb': 1,
            'max_documents': 50,
            'max_invoices_monthly': 10,
            'max_employees': 5,
            'max_projects': 2,
            # Feature Flags
            'has_ai_assistant': False,
            'has_advanced_analytics': False,
            'has_custom_reports': False,
            'has_api_access': False,
            'has_priority_support': False,
            'has_sso': False,
            'has_audit_logs': False,
            'has_data_export': True,
            'has_multi_currency': False,
            'has_custom_branding': False,
            # AI Limits
            'ai_queries_monthly': 0,
            'rag_documents': 0,
            # Status
            'is_active': True,
            'is_popular': False,
            'sort_order': 1,
        }
    )
    
    # Pro Plan
    SubscriptionPlan.objects.update_or_create(
        plan_type='pro',
        defaults={
            'name': 'Pro',
            'name_en': 'Pro',
            'name_zh': '專業版',
            'description': 'For growing businesses that need more power.',
            'description_en': 'For growing businesses that need more power.',
            'description_zh': '適合需要更多功能的成長型企業。',
            # Pricing
            'price_monthly': 29,
            'price_yearly': 290,  # ~17% discount
            'currency': 'USD',
            # Limits
            'max_users': 5,
            'max_companies': 3,
            'max_storage_gb': 10,
            'max_documents': 500,
            'max_invoices_monthly': 100,
            'max_employees': 25,
            'max_projects': 10,
            # Feature Flags
            'has_ai_assistant': True,
            'has_advanced_analytics': True,
            'has_custom_reports': True,
            'has_api_access': False,
            'has_priority_support': False,
            'has_sso': False,
            'has_audit_logs': True,
            'has_data_export': True,
            'has_multi_currency': True,
            'has_custom_branding': False,
            # AI Limits
            'ai_queries_monthly': 500,
            'rag_documents': 50,
            # Status
            'is_active': True,
            'is_popular': True,  # Mark as popular/recommended
            'sort_order': 2,
        }
    )
    
    # Pro+ Enterprise Plan
    SubscriptionPlan.objects.update_or_create(
        plan_type='pro_plus',
        defaults={
            'name': 'Pro+ Enterprise',
            'name_en': 'Pro+ Enterprise',
            'name_zh': '企業旗艦版',
            'description': 'For large organizations with advanced needs.',
            'description_en': 'For large organizations with advanced needs.',
            'description_zh': '適合需要進階功能的大型企業。',
            # Pricing
            'price_monthly': 99,
            'price_yearly': 990,  # ~17% discount
            'currency': 'USD',
            # Limits - Use 0 for unlimited
            'max_users': 0,  # Unlimited
            'max_companies': 0,  # Unlimited
            'max_storage_gb': 100,
            'max_documents': 0,  # Unlimited
            'max_invoices_monthly': 0,  # Unlimited
            'max_employees': 0,  # Unlimited
            'max_projects': 0,  # Unlimited
            # Feature Flags - All enabled
            'has_ai_assistant': True,
            'has_advanced_analytics': True,
            'has_custom_reports': True,
            'has_api_access': True,
            'has_priority_support': True,
            'has_sso': True,
            'has_audit_logs': True,
            'has_data_export': True,
            'has_multi_currency': True,
            'has_custom_branding': True,
            # AI Limits
            'ai_queries_monthly': 0,  # Unlimited
            'rag_documents': 0,  # Unlimited (or set high limit)
            # Status
            'is_active': True,
            'is_popular': False,
            'sort_order': 3,
        }
    )


def reverse_seed(apps, schema_editor):
    """Remove seeded subscription plans"""
    SubscriptionPlan = apps.get_model('users', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(plan_type__in=['free', 'pro', 'pro_plus']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_url_user_language_user_phone_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_subscription_plans, reverse_seed),
    ]
