# Generated by Django 6.0 on 2025-12-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='acc_account_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='acc_account_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='acc_contact_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='acc_contact_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='acc_expense_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='acc_expense_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='acc_invoice_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='acc_invoice_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='acc_invoice_issue_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='acc_invoice_type_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='acc_invoice_contact_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoiceline',
            name='acc_invline_invoice_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='acc_je_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='acc_je_entry_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='acc_je_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='acc_payment_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='acc_payment_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='acc_payment_created_idx',
        ),
    ]
