# Generated by Django 6.0 on 2025-12-08 14:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_add_project_models'),
        ('core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='receipts/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('recognition_status', models.CharField(choices=[('PENDING', 'PENDING'), ('RECOGNIZED', 'RECOGNIZED'), ('UNRECOGNIZED', 'UNRECOGNIZED'), ('MANUALLY_CLASSIFIED', 'MANUALLY_CLASSIFIED')], default='PENDING', max_length=30)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('confidence_threshold', models.DecimalField(decimal_places=4, default=Decimal('0.7000'), help_text='Minimum confidence for automatic recognition', max_digits=5)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency_code', models.CharField(blank=True, default='TWD', max_length=3)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True)),
                ('manual_vendor', models.CharField(blank=True, max_length=255)),
                ('manual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('manual_date', models.DateField(blank=True, null=True)),
                ('classification_notes', models.TextField(blank=True)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('classified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_receipts', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_receipts', to='accounting.expense')),
                ('manual_category', models.ForeignKey(blank=True, help_text='Manually assigned expense category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorized_receipts', to='accounting.account')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounting.project')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recognition_status', 'created_at'], name='accounting__recogni_ef5fd2_idx'), models.Index(fields=['batch_id'], name='accounting__batch_i_29d13a_idx'), models.Index(fields=['tenant', 'recognition_status'], name='accounting__tenant__e687ec_idx')],
            },
        ),
    ]
