# Generated by Django 6.0 on 2025-12-08 14:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_add_receipt_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field_type', models.CharField(choices=[('VENDOR', 'VENDOR'), ('TOTAL', 'TOTAL'), ('DATE', 'DATE'), ('CURRENCY', 'CURRENCY'), ('TAX', 'TAX'), ('CATEGORY', 'CATEGORY'), ('SUBTOTAL', 'SUBTOTAL'), ('TIP', 'TIP'), ('PAYMENT_METHOD', 'PAYMENT_METHOD'), ('INVOICE_NUMBER', 'INVOICE_NUMBER'), ('LINE_ITEM', 'LINE_ITEM'), ('OTHER', 'OTHER')], max_length=30)),
                ('field_name', models.CharField(max_length=100)),
                ('raw_value', models.TextField(blank=True)),
                ('normalized_value', models.TextField(blank=True)),
                ('data_type', models.CharField(default='string', help_text='string, number, date, currency', max_length=20)),
                ('bbox_x1', models.FloatField(blank=True, help_text='Left coordinate', null=True)),
                ('bbox_y1', models.FloatField(blank=True, help_text='Top coordinate', null=True)),
                ('bbox_x2', models.FloatField(blank=True, help_text='Right coordinate', null=True)),
                ('bbox_y2', models.FloatField(blank=True, help_text='Bottom coordinate', null=True)),
                ('bbox_unit', models.CharField(default='ratio', help_text='ratio (0-1) or pixel', max_length=10)),
                ('page_number', models.PositiveSmallIntegerField(default=1, help_text='Page number for multi-page receipts')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('is_corrected', models.BooleanField(default=False)),
                ('corrected_value', models.TextField(blank=True)),
                ('corrected_bbox_x1', models.FloatField(blank=True, null=True)),
                ('corrected_bbox_y1', models.FloatField(blank=True, null=True)),
                ('corrected_bbox_x2', models.FloatField(blank=True, null=True)),
                ('corrected_bbox_y2', models.FloatField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_fields', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='accounting.receipt')),
            ],
            options={
                'ordering': ['field_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldCorrectionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField()),
                ('previous_value', models.TextField(blank=True)),
                ('previous_bbox_x1', models.FloatField(blank=True, null=True)),
                ('previous_bbox_y1', models.FloatField(blank=True, null=True)),
                ('previous_bbox_x2', models.FloatField(blank=True, null=True)),
                ('previous_bbox_y2', models.FloatField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True)),
                ('new_bbox_x1', models.FloatField(blank=True, null=True)),
                ('new_bbox_y1', models.FloatField(blank=True, null=True)),
                ('new_bbox_x2', models.FloatField(blank=True, null=True)),
                ('new_bbox_y2', models.FloatField(blank=True, null=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('correction_source', models.CharField(default='MANUAL', help_text='MANUAL, AI_SUGGESTION, BATCH_UPDATE', max_length=30)),
                ('corrected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_corrections', to=settings.AUTH_USER_MODEL)),
                ('extracted_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_history', to='accounting.extractedfield')),
            ],
            options={
                'verbose_name': 'Field Correction History',
                'verbose_name_plural': 'Field Correction Histories',
                'ordering': ['-corrected_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptCorrectionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_fields', models.PositiveIntegerField(default=0)),
                ('corrected_fields', models.PositiveIntegerField(default=0)),
                ('total_corrections', models.PositiveIntegerField(default=0)),
                ('first_corrected_at', models.DateTimeField(blank=True, null=True)),
                ('last_corrected_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_by_users', models.JSONField(blank=True, default=list)),
                ('original_avg_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction_summary', to='accounting.receipt')),
            ],
            options={
                'verbose_name': 'Receipt Correction Summary',
                'verbose_name_plural': 'Receipt Correction Summaries',
            },
        ),
        migrations.AddIndex(
            model_name='extractedfield',
            index=models.Index(fields=['receipt', 'field_type'], name='accounting__receipt_1435d9_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedfield',
            index=models.Index(fields=['is_corrected'], name='accounting__is_corr_0257bf_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldcorrectionhistory',
            index=models.Index(fields=['extracted_field', 'version'], name='accounting__extract_46461d_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldcorrectionhistory',
            index=models.Index(fields=['corrected_by', 'corrected_at'], name='accounting__correct_917953_idx'),
        ),
    ]
