# Generated by Django 5.2.9 on 2025-12-05 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='receipts/%Y/%m/')),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded / 已上傳'), ('ANALYZING', 'Analyzing / 分析中'), ('ANALYZED', 'Analyzed / 已分析'), ('CATEGORIZED', 'Categorized / 已分類'), ('JOURNAL_CREATED', 'Journal Created / 已建分錄'), ('APPROVED', 'Approved / 已核准'), ('POSTED', 'Posted / 已過帳'), ('REJECTED', 'Rejected / 已拒絕'), ('ERROR', 'Error / 錯誤')], default='UPLOADED', max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('receipt_time', models.TimeField(blank=True, null=True)),
                ('currency', models.CharField(default='TWD', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_method', models.CharField(default='CASH', max_length=20)),
                ('category', models.CharField(choices=[('MEALS', 'Meals / 伙食費'), ('TRANSPORTATION', 'Transportation / 交通費'), ('OFFICE_SUPPLIES', 'Office Supplies / 辦公用品'), ('UTILITIES', 'Utilities / 水電費'), ('ENTERTAINMENT', 'Entertainment / 交際費'), ('RENT', 'Rent / 租金'), ('TELEPHONE', 'Telephone / 電話費'), ('INSURANCE', 'Insurance / 保險費'), ('MAINTENANCE', 'Maintenance / 維修費'), ('TRAVEL', 'Travel / 差旅費'), ('TRAINING', 'Training / 培訓費'), ('OTHER', 'Other / 其他')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('ai_raw_response', models.JSONField(blank=True, default=dict)),
                ('ai_confidence_score', models.FloatField(default=0)),
                ('ai_suggestions', models.JSONField(blank=True, default=list)),
                ('ai_warnings', models.JSONField(blank=True, default=list)),
                ('detected_language', models.CharField(default='auto', max_length=10)),
                ('journal_entry_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounting.expense')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounting.journalentry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipts', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt / 收據',
                'verbose_name_plural': 'Receipts / 收據',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_count', models.IntegerField(default=0)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to=settings.AUTH_USER_MODEL)),
                ('receipts', models.ManyToManyField(related_name='reports', to='ai_assistants.receipt')),
            ],
            options={
                'verbose_name': 'Expense Report / 費用報表',
                'verbose_name_plural': 'Expense Reports / 費用報表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptComparison',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('excel_file', models.FileField(upload_to='comparisons/%Y/%m/')),
                ('excel_filename', models.CharField(max_length=255)),
                ('total_excel_records', models.IntegerField(default=0)),
                ('total_db_records', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('missing_in_db_count', models.IntegerField(default=0)),
                ('missing_in_excel_count', models.IntegerField(default=0)),
                ('amount_mismatch_count', models.IntegerField(default=0)),
                ('comparison_details', models.JSONField(default=dict)),
                ('ai_analysis', models.JSONField(default=dict)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('health_score', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Comparison / 收據比對',
                'verbose_name_plural': 'Receipt Comparisons / 收據比對',
                'ordering': ['-created_at'],
            },
        ),
    ]
