# Generated by Django 6.0 on 2025-12-05 21:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistants', '0002_aidocument_brainstormsession_brainstormidea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('agent_type', models.CharField(choices=[('BRAINSTORM', 'Brainstorming Assistant'), ('EMAIL', 'Email Assistant'), ('DOCUMENT', 'Document Assistant'), ('PLANNER', 'Planner Assistant'), ('BUSINESS', 'Business CRUD Agent'), ('ANALYST', 'Data Analyst Agent'), ('GENERAL', 'General Purpose Agent')], default='GENERAL', max_length=30)),
                ('allowed_tools', models.JSONField(default=list, help_text='List of tool IDs this agent can use')),
                ('auto_execute', models.BooleanField(default=False, help_text='Execute actions without approval')),
                ('max_auto_actions', models.IntegerField(default=10, help_text='Max actions per session without approval')),
                ('llm_provider', models.CharField(default='openai', max_length=50)),
                ('llm_model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('system_prompt', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('messages', models.JSONField(default=list, help_text='Chat history [{role, content, timestamp}]')),
                ('context', models.JSONField(default=dict, help_text='Additional context for AI')),
                ('total_actions', models.IntegerField(default=0)),
                ('successful_actions', models.IntegerField(default=0)),
                ('failed_actions', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='ai_assistants.aiagent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Group actions in same conversation', max_length=100)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create Record'), ('UPDATE', 'Update Record'), ('DELETE', 'Delete Record'), ('BULK_CREATE', 'Bulk Create'), ('BULK_UPDATE', 'Bulk Update'), ('BULK_DELETE', 'Bulk Delete'), ('QUERY', 'Query Data'), ('ANALYZE', 'Analyze Data')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed Successfully'), ('ROLLED_BACK', 'Rolled Back'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected by User')], default='PENDING', max_length=20)),
                ('target_model', models.CharField(help_text='e.g., business.AuditProject', max_length=100)),
                ('target_id', models.CharField(blank=True, help_text='Record ID if applicable', max_length=100)),
                ('data_before', models.JSONField(default=dict, help_text='State before action (for rollback)')),
                ('data_after', models.JSONField(default=dict, help_text='State after action / intended change')),
                ('user_prompt', models.TextField(blank=True, help_text='Original user request')),
                ('ai_reasoning', models.TextField(blank=True, help_text='Why AI decided to take this action')),
                ('ai_confidence', models.FloatField(default=0, help_text='AI confidence score 0-1')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_duration_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_reason', models.TextField(blank=True)),
                ('parent_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_actions', to='ai_assistants.aiactionlog')),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_back_actions', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_action_logs', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='ai_assistants.aiagent')),
            ],
            options={
                'verbose_name': 'AI Action Log',
                'verbose_name_plural': 'AI Action Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', '-created_at'], name='ai_assistan_session_e68392_idx'), models.Index(fields=['target_model', 'target_id'], name='ai_assistan_target__c78937_idx'), models.Index(fields=['status', '-created_at'], name='ai_assistan_status_658680_idx')],
            },
        ),
    ]
