# Generated by Django 6.0 on 2025-12-07 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistants', '0003_aiagent_aiconversation_aiactionlog'),
        ('business', '0004_businesspartner_ipodealfunnel_ipodealsize_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainstormMeeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Meeting title / 會議標題', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Meeting description / 會議描述')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled / 已排程'), ('IN_PROGRESS', 'In Progress / 進行中'), ('COMPLETED', 'Completed / 已完成'), ('CANCELLED', 'Cancelled / 已取消'), ('POSTPONED', 'Postponed / 已延期')], default='SCHEDULED', max_length=20)),
                ('scheduled_start', models.DateTimeField(help_text='Scheduled start time / 預定開始時間')),
                ('scheduled_end', models.DateTimeField(help_text='Scheduled end time / 預定結束時間')),
                ('actual_start', models.DateTimeField(blank=True, help_text='Actual start time / 實際開始時間', null=True)),
                ('actual_end', models.DateTimeField(blank=True, help_text='Actual end time / 實際結束時間', null=True)),
                ('location', models.CharField(blank=True, help_text='Meeting location / 會議地點', max_length=500)),
                ('meeting_link', models.URLField(blank=True, help_text='Online meeting link / 線上會議連結')),
                ('meeting_type', models.CharField(choices=[('IN_PERSON', 'In Person / 實體'), ('ONLINE', 'Online / 線上'), ('HYBRID', 'Hybrid / 混合')], default='IN_PERSON', max_length=30)),
                ('agenda', models.TextField(blank=True, help_text='Meeting agenda / 會議議程')),
                ('objectives', models.JSONField(default=list, help_text='Meeting objectives / 會議目標')),
                ('meeting_notes', models.TextField(blank=True, help_text='Meeting notes / 會議記錄')),
                ('summary', models.TextField(blank=True, help_text='Meeting summary / 會議總結')),
                ('action_items', models.JSONField(default=list, help_text='Action items [{task, assignee, deadline}]')),
                ('decisions_made', models.JSONField(default=list, help_text='Decisions made during meeting / 會議決定')),
                ('ideas_generated', models.JSONField(default=list, help_text='Ideas generated during brainstorming / 腦力激盪產生的想法')),
                ('selected_ideas', models.JSONField(default=list, help_text='Selected/voted ideas / 選中/投票的想法')),
                ('max_participants', models.IntegerField(default=20, help_text='Maximum number of participants / 最大參與人數')),
                ('tags', models.JSONField(default=list, help_text='Meeting tags / 會議標籤')),
                ('attachments', models.JSONField(default=list, help_text='Meeting attachments [{name, url, type}]')),
                ('organizer', models.ForeignKey(help_text='Meeting organizer / 會議組織者', on_delete=django.db.models.deletion.CASCADE, related_name='organized_brainstorm_meetings', to=settings.AUTH_USER_MODEL)),
                ('related_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brainstorm_meetings', to='business.bmiipoprrecord')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brainstorm_meetings', to='business.company')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brainstorm_meetings', to='business.auditproject')),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='ai_assistants.brainstormsession')),
            ],
            options={
                'verbose_name': 'Brainstorm Meeting / 腦力激盪會議',
                'verbose_name_plural': 'Brainstorm Meetings / 腦力激盪會議',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='BrainstormMeetingParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ORGANIZER', 'Organizer / 組織者'), ('FACILITATOR', 'Facilitator / 主持人'), ('PRESENTER', 'Presenter / 報告者'), ('PARTICIPANT', 'Participant / 參與者'), ('OBSERVER', 'Observer / 旁聽者'), ('NOTETAKER', 'Note Taker / 記錄者')], default='PARTICIPANT', max_length=20)),
                ('status', models.CharField(choices=[('INVITED', 'Invited / 已邀請'), ('ACCEPTED', 'Accepted / 已接受'), ('DECLINED', 'Declined / 已拒絕'), ('TENTATIVE', 'Tentative / 暫定'), ('ATTENDED', 'Attended / 已出席'), ('NO_SHOW', 'No Show / 未出席')], default='INVITED', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When participant responded / 參與者回覆時間', null=True)),
                ('response_notes', models.TextField(blank=True, help_text='Response notes / 回覆備註')),
                ('joined_at', models.DateTimeField(blank=True, help_text='When participant joined / 參與者加入時間', null=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When participant left / 參與者離開時間', null=True)),
                ('ideas_contributed', models.IntegerField(default=0, help_text='Number of ideas contributed / 貢獻的想法數量')),
                ('votes_cast', models.IntegerField(default=0, help_text='Number of votes cast / 投票數量')),
                ('notes', models.TextField(blank=True, help_text='Personal notes / 個人備註')),
                ('is_external', models.BooleanField(default=False, help_text='Is external participant / 是否為外部參與者')),
                ('external_name', models.CharField(blank=True, help_text='External participant name / 外部參與者姓名', max_length=255)),
                ('external_email', models.EmailField(blank=True, help_text='External participant email / 外部參與者電郵', max_length=254)),
                ('external_company', models.CharField(blank=True, help_text='External participant company / 外部參與者公司', max_length=255)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ai_assistants.brainstormmeeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brainstorm_meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Participant / 會議參與者',
                'verbose_name_plural': 'Meeting Participants / 會議參與者',
                'ordering': ['role', 'user__full_name'],
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
