# Generated by Django 6.0 on 2025-12-07 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistants', '0004_brainstormmeeting_brainstormmeetingparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brainstormmeetingparticipant',
            options={'ordering': ['role', '-created_at'], 'verbose_name': 'Meeting Participant / 會議參與者', 'verbose_name_plural': 'Meeting Participants / 會議參與者'},
        ),
        migrations.AlterUniqueTogether(
            name='brainstormmeetingparticipant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='brainstormmeetingparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brainstorm_meeting_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
