# Generated by Django 6.0 on 2025-12-07 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_account_acc_account_type_idx_and_more'),
        ('ai_assistants', '0005_alter_brainstormmeetingparticipant_options_and_more'),
        ('business', '0004_businesspartner_ipodealfunnel_ipodealsize_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldExtraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='Field name (e.g., vendor_name, total_amount)', max_length=100)),
                ('extracted_value', models.TextField(help_text='Extracted value / 提取的值')),
                ('corrected_value', models.TextField(blank=True, help_text='User corrected value / 用戶校正的值', null=True)),
                ('confidence', models.FloatField(default=0, help_text='AI confidence score 0-1 / AI置信度分數')),
                ('bounding_box', models.JSONField(blank=True, default=dict, help_text='Bounding box coordinates {"x": 0, "y": 0, "width": 100, "height": 20}')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Field Extraction / 欄位提取',
                'verbose_name_plural': 'Field Extractions / 欄位提取',
                'ordering': ['receipt', 'field_name'],
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='unrecognized_reason',
            field=models.TextField(blank=True, help_text='Reason why document could not be recognized / 無法識別的原因', null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded / 已上傳'), ('ANALYZING', 'Analyzing / 分析中'), ('ANALYZED', 'Analyzed / 已分析'), ('CATEGORIZED', 'Categorized / 已分類'), ('UNRECOGNIZED', 'Unrecognized / 無法識別'), ('PENDING_REVIEW', 'Pending Review / 待審核'), ('JOURNAL_CREATED', 'Journal Created / 已建分錄'), ('APPROVED', 'Approved / 已核准'), ('POSTED', 'Posted / 已過帳'), ('REJECTED', 'Rejected / 已拒絕'), ('ERROR', 'Error / 錯誤')], default='UPLOADED', max_length=20),
        ),
        migrations.CreateModel(
            name='AccountingProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name / 專案名稱', max_length=255)),
                ('code', models.CharField(help_text='Project code / 專案編號', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('AUDIT', 'Audit / 審計'), ('TAX', 'Tax Return / 報稅'), ('BOOKKEEPING', 'Bookkeeping / 記帳'), ('CONSULTING', 'Consulting / 諮詢'), ('OTHER', 'Other / 其他')], default='BOOKKEEPING', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / 草稿'), ('ACTIVE', 'Active / 進行中'), ('PENDING_REVIEW', 'Pending Review / 待審核'), ('COMPLETED', 'Completed / 已完成'), ('ARCHIVED', 'Archived / 已歸檔'), ('CANCELLED', 'Cancelled / 已取消')], default='DRAFT', max_length=20)),
                ('fiscal_year', models.IntegerField(help_text='Fiscal year / 財務年度')),
                ('quarter', models.IntegerField(blank=True, choices=[(1, 'Q1 / 第一季'), (2, 'Q2 / 第二季'), (3, 'Q3 / 第三季'), (4, 'Q4 / 第四季')], help_text='Fiscal quarter (optional) / 財務季度（選填）', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, help_text='Project deadline / 截止日期', null=True)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage 0-100 / 進度百分比')),
                ('budget_hours', models.DecimalField(decimal_places=2, default=0, help_text='Budgeted hours / 預算工時', max_digits=10)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, help_text='Actual hours spent / 實際工時', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='Client company / 客戶公司', on_delete=django.db.models.deletion.CASCADE, related_name='accounting_projects', to='business.company')),
                ('owner', models.ForeignKey(help_text='Project owner / 專案負責人', on_delete=django.db.models.deletion.PROTECT, related_name='owned_accounting_projects', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, help_text='Team members / 團隊成員', related_name='accounting_project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Project / 會計專案',
                'verbose_name_plural': 'Accounting Projects / 會計專案',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Associated accounting project / 關聯的會計專案', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='ai_assistants.accountingproject'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['project', 'status'], name='ai_assistan_project_aed89f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['uploaded_by', 'status'], name='ai_assistan_uploade_ba04db_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_date'], name='ai_assistan_receipt_64c8f5_idx'),
        ),
        migrations.AddField(
            model_name='fieldextraction',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_extractions', to='ai_assistants.receipt'),
        ),
        migrations.AddField(
            model_name='fieldextraction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_extractions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountingproject',
            index=models.Index(fields=['company', 'fiscal_year'], name='ai_assistan_company_f40768_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingproject',
            index=models.Index(fields=['status'], name='ai_assistan_status_5bd334_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingproject',
            index=models.Index(fields=['owner'], name='ai_assistan_owner_i_711af7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldextraction',
            unique_together={('receipt', 'field_name')},
        ),
    ]
