# Generated by Django 5.2.9 on 2025-12-05 19:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='BMIIPOPRRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('INITIAL_ASSESSMENT', 'INITIAL_ASSESSMENT'), ('DUE_DILIGENCE', 'DUE_DILIGENCE'), ('DOCUMENTATION', 'DOCUMENTATION'), ('REGULATORY_FILING', 'REGULATORY_FILING'), ('MARKETING', 'MARKETING'), ('PRICING', 'PRICING'), ('LISTING', 'LISTING'), ('POST_IPO', 'POST_IPO')], default='INITIAL_ASSESSMENT', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ON_TRACK', 'ON_TRACK'), ('DELAYED', 'DELAYED'), ('AT_RISK', 'AT_RISK'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', max_length=20)),
                ('project_type', models.CharField(default='IPO', help_text='IPO, PR, RIGHTS_ISSUE, PLACEMENT', max_length=20)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated deal value', max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total project cost', max_digits=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('lead_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_bmi_projects', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='bmi_team_memberships', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bmi_projects', to='business.company')),
            ],
            options={
                'verbose_name': 'BMI IPO/PR Record',
                'verbose_name_plural': 'BMI IPO/PR Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BMIDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bmi_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='business.bmiipoprrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillableHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_reference', models.CharField(blank=True, help_text='Reference to audit/tax return or other project', max_length=255)),
                ('role', models.CharField(choices=[('CLERK', 'CLERK'), ('ACCOUNTANT', 'ACCOUNTANT'), ('MANAGER', 'MANAGER'), ('DIRECTOR', 'DIRECTOR'), ('PARTNER', 'PARTNER')], default='CLERK', max_length=20)),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Base hourly rate before multiplier', max_digits=10)),
                ('hourly_rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Rate multiplier based on role', max_digits=5)),
                ('date', models.DateField()),
                ('actual_hours', models.DecimalField(decimal_places=2, help_text='Hours worked', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True, help_text='Work description')),
                ('is_billable', models.BooleanField(default=True)),
                ('is_invoiced', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billable_hours', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, help_text='Client company being billed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billable_hours', to='business.company')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fiscal_year', models.CharField(help_text='e.g., 2024, 2024-Q1', max_length=20)),
                ('audit_type', models.CharField(default='FINANCIAL', help_text='FINANCIAL, TAX, INTERNAL, COMPLIANCE', max_length=50)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('PLANNING', 'PLANNING'), ('FIELDWORK', 'FIELDWORK'), ('REVIEW', 'REVIEW'), ('REPORTING', 'REPORTING'), ('COMPLETED', 'COMPLETED'), ('ON_HOLD', 'ON_HOLD')], default='NOT_STARTED', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('budget_hours', models.DecimalField(decimal_places=2, default=0, help_text='Budgeted hours for this audit', max_digits=10)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, help_text='Actual hours spent', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audits', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='audit_team_memberships', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_projects', to='business.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PARTIAL', 'PARTIAL'), ('RECEIVED', 'RECEIVED'), ('OVERDUE', 'OVERDUE'), ('WRITTEN_OFF', 'WRITTEN_OFF')], default='PENDING', max_length=20)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='business.company')),
            ],
            options={
                'verbose_name_plural': 'Revenues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxReturnCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_year', models.CharField(help_text='e.g., 2024', max_length=20)),
                ('tax_type', models.CharField(default='PROFITS_TAX', help_text='PROFITS_TAX, SALARIES_TAX, PROPERTY_TAX, STAMP_DUTY', max_length=50)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('SUBMITTED', 'SUBMITTED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('AMENDED', 'AMENDED')], default='PENDING', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=15)),
                ('documents_received', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_returns', to='business.company')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_tax_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deadline', '-created_at'],
            },
        ),
    ]
