# Generated by Django 6.0 on 2025-12-06 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_clientindustry_mediasentimentrecord_activeengagement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revenuetrend',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mediasentimentrecord',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this sentiment record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_records', to='business.company'),
        ),
        migrations.AddField(
            model_name='revenuetrend',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this revenue trend belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_trends', to='business.company'),
        ),
        migrations.AlterUniqueTogether(
            name='revenuetrend',
            unique_together={('company', 'period_year', 'period_month')},
        ),
    ]
