# Generated by Django 6.0 on 2025-12-06 06:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_revenuetrend_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(choices=[('KOL', 'KOL/Influencer'), ('MEDIA', 'Media Partner'), ('AGENCY', 'Agency'), ('VENDOR', 'Vendor/Supplier'), ('CONSULTANT', 'Consultant'), ('LEGAL', 'Legal Firm'), ('FINANCIAL', 'Financial Advisor'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PROSPECT', 'Prospect'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('service_description', models.TextField(blank=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('rating', models.IntegerField(default=0, help_text='Partner rating 0-5 stars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_partners', to='business.company')),
            ],
            options={
                'verbose_name': 'Business Partner',
                'verbose_name_plural': 'Business Partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPODealFunnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('period_date', models.DateField()),
                ('stage', models.CharField(choices=[('LEADS', 'Leads'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal'), ('DUE_DILIGENCE', 'Due Diligence'), ('FILING', 'Filing'), ('LISTED', 'Listed')], default='LEADS', max_length=30)),
                ('deal_count', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Conversion rate to this stage (%)', max_digits=5)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_deal_funnel', to='business.company')),
            ],
            options={
                'verbose_name': 'IPO Deal Funnel',
                'verbose_name_plural': 'IPO Deal Funnel Records',
                'ordering': ['-period_date', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='IPODealSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('period_date', models.DateField()),
                ('size_category', models.CharField(choices=[('MEGA', 'Mega (>$1B)'), ('LARGE', 'Large ($500M-1B)'), ('MID', 'Mid ($100-500M)'), ('SMALL', 'Small (<$100M)')], default='MID', max_length=20)),
                ('deal_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deal amount in millions', max_digits=18)),
                ('avg_deal_size', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_deal_sizes', to='business.company')),
            ],
            options={
                'verbose_name': 'IPO Deal Size',
                'verbose_name_plural': 'IPO Deal Size Records',
                'ordering': ['-period_date', 'size_category'],
            },
        ),
        migrations.CreateModel(
            name='IPOTimelineProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phase', models.CharField(choices=[('DUE_DILIGENCE', 'Due Diligence'), ('DOCUMENTATION', 'Documentation'), ('REGULATORY', 'Regulatory Filing'), ('MARKETING', 'Marketing/Roadshow')], default='DUE_DILIGENCE', max_length=30)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='IN_PROGRESS', help_text='NOT_STARTED, IN_PROGRESS, COMPLETED, DELAYED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_timeline_progress', to='business.company')),
                ('ipo_mandate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_progress', to='business.ipomandate')),
            ],
            options={
                'verbose_name': 'IPO Timeline Progress',
                'verbose_name_plural': 'IPO Timeline Progress Records',
                'ordering': ['company', 'phase'],
                'unique_together': {('company', 'ipo_mandate', 'phase')},
            },
        ),
    ]
