# Generated by Django 5.1.4 on 2025-07-27 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
