# Generated by Django 5.2.9 on 2025-12-05 19:28

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='GENERAL', help_text='FINANCIAL, OPERATIONAL, SALES, HR, etc.', max_length=50)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('target_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('previous_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('unit', models.CharField(blank=True, help_text='%, $, units, etc.', max_length=20)),
                ('display_format', models.CharField(default='NUMBER', help_text='NUMBER, CURRENCY, PERCENTAGE', max_length=20)),
                ('trend', models.CharField(default='NEUTRAL', help_text='UP, DOWN, NEUTRAL', max_length=10)),
                ('is_positive_good', models.BooleanField(default=True, help_text='True if higher value is better')),
                ('period', models.CharField(blank=True, help_text='2024-Q4, 2024-12, etc.', max_length=20)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(help_text='SALES, FINANCIAL, HR, AUDIT, etc.', max_length=50)),
                ('frequency', models.CharField(default='MONTHLY', help_text='DAILY, WEEKLY, MONTHLY, QUARTERLY, ANNUALLY', max_length=20)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict, help_text='Report configuration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='chart',
            options={'ordering': ['position', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.AddField(
            model_name='chart',
            name='data_source',
            field=models.CharField(blank=True, help_text='API endpoint or data source name', max_length=100),
        ),
        migrations.AddField(
            model_name='chart',
            name='height',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='chart',
            name='position',
            field=models.IntegerField(default=0, help_text='Position in dashboard'),
        ),
        migrations.AddField(
            model_name='chart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='width',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='layout',
            field=models.JSONField(blank=True, default=dict, help_text='Dashboard layout configuration'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(choices=[('bar', 'Bar'), ('pie', 'Pie'), ('line', 'Line'), ('scatter', 'Scatter'), ('area', 'Area'), ('donut', 'Donut'), ('radar', 'Radar'), ('table', 'Table'), ('metric', 'Metric Card'), ('unsupported', 'Unsupported')], max_length=20),
        ),
        migrations.CreateModel(
            name='AnalyticsSales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue for the month', max_digits=15)),
                ('target_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue target for the month', max_digits=15)),
                ('growth_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Month-over-month growth percentage', max_digits=6)),
                ('yoy_growth', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Year-over-year growth percentage', max_digits=6)),
                ('new_clients', models.IntegerField(default=0, help_text='Number of new clients acquired')),
                ('total_clients', models.IntegerField(default=0, help_text='Total active clients')),
                ('churned_clients', models.IntegerField(default=0, help_text='Clients lost this month')),
                ('churn_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Client churn rate percentage', max_digits=5)),
                ('deals_closed', models.IntegerField(default=0)),
                ('deals_pipeline', models.IntegerField(default=0)),
                ('average_deal_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lead to client conversion rate', max_digits=5)),
                ('operating_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('marketing_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sales Analytics',
                'verbose_name_plural': 'Sales Analytics',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
